### ISSUE TITLE
Installation on Ubuntu 14.04

### ISSUE THREAD

**Issue by Netifriik** [helpyio/helpy#10]
The Installation section is not very friendly unless using Heroku. Any suggestions on how do install it on a Ubuntu machine?

**Comment by scott** [comment]
I actually have not tried installing it on Ubuntu yet, but it should be fairly straightforward.  I will try to give it a try this weekend and let you know how it goes.  Do you have Ruby 2.2 and Rails 4.2 installed?

**Comment by Netifriik** [comment]
I do. I'm already in the process of trying to install Helpy. I've got the settings configured, installed postgre and Ruby + Rails, seeded the database. But how do I run Helpy itself?

**Comment by Netifriik** [comment]
Alright. I got it working on Ubuntu. I ran this command manually `bundle exec unicorn_rails -p 8888 -c ./config/unicorn.rb`

The only I ran into while trying to get this working was setting up the postgre database with Helpy. I needed to manually create an user and the database.

**Comment by Netifriik** [comment]
Helpy seems to be very slow for me. Each page loads for about 10-60 seconds while my other pages load in less than 1 second. What could be the problem?

**Comment by scott** [comment]
Hmm that sounds like it could be an environment issue, like the database connection is slowing things up?  To start it in production try `bundle exec unicorn_rails -p 8888 -E production -c ./config/unicorn.rb`

**Comment by Netifriik** [comment]
Seems to be working perfectly now! :+1:

**Comment by scott** [comment]
That would be great, and would be a big help to other users in Estonia :)

**Comment by Netifriik** [comment]
This is the template file:
https://gist.github.com/Netifriik/7181c212ede116d6d420

Hope it helps :)

**Comment by scott** [comment]
Thanks!  I will add it into the app.  I am also interested in any suggestions you might have to make Helpy better?

**Comment by wmakley** [comment]
I am having a similar problem with my own Debian server. Is unicorn required? I am trying to get it going in a Passenger environment (just what we have, makes running lots of small sites on one server easier). In my experience with unicorn, the app server shouldn't really affect any functionality, but I am getting some errors, so I thought I would check.

**Comment by scott** [comment]
I wrote a tutorial for installing on Ubuntu 14.04 with Passenger at http://support.helpy.io/en/knowledgebase/11-installing-helpy/docs/27-installing-helpy-on-ubuntu-14-04-using-passenger-and-nginx
