### ISSUE TITLE
Admin Inbox: Categories under Custom Views returns an empty list after reload

### ISSUE THREAD

**Issue by cr0vy** [helpyio/helpy#1018]
After reload Custom Views topic -site with url such as: `example.com/admin/topics?box_id=11&locale=en`, you get empty ticket list. List isn't clearing itself, if you are under some of the default categories (New, Mine, Pending, SLA Violation).

Reproduce
1. Open Admin Inbox site
2. Select some category from Custom Views
3. Select another category from Custom Views
4. Click browser Reload button, click Ctrl+R, or click Ctrl+Shift+R

![issue_screenshot](https://user-images.githubusercontent.com/43742796/48185890-18018e00-e33f-11e8-907a-14a68e2b91fa.png)

**Comment by scott** [comment]
This has been moved to our internal bug tracking since it is not an issue with the open source core.  The issue is still open, thanks for submitting.
