### ISSUE TITLE
Cloudinary upload doesn't work anymore on doc edition

### ISSUE THREAD

**Issue by Pyo25** [helpyio/helpy#1038]
Hi @scott,

I realized the image upload doesn't work anymore when editing a Doc. 
It works well with the 2.1.0 release but not on master.

When selecting a file, nothing happens. The image is not uploaded at all on Cloudinary. It's like the Cloudinary jQuery plugin is not loaded.  

Do you have an idea where it could come from? I'd happy to investigate and open a PR!

Cheers

**Comment by scott** [comment]
Hey @Pyo25 
hmmm well we updated the cloudinary gem version recently so that might be a place to start...
https://github.com/helpyio/helpy/pull/908

**Comment by scott** [comment]
Hey @Pyo25 did you ever figure this one out?  Was there a bug or was it something else?

**Comment by scott** [comment]
If you can confirm or reproduce this, please reopen!
