### ISSUE TITLE
Feature Request: Canned Responses

### ISSUE THREAD

**Issue by olliebennett** [helpyio/helpy#104]
An option to send a pre-defined message to a user. Typically used to respond quickly to recurring questions.

**Comment by scott** [comment]
Already exists, and is multilingual  :)  

![screen shot 2016-03-24 at 3 29 13 pm](https://cloud.githubusercontent.com/assets/14369/14031967/360e7bd2-f1d5-11e5-898e-d0c22b465cda.png)

**Comment by olliebennett** [comment]
Well... that's awkward! Sorry!

**Comment by scott** [comment]
No worries, I am glad you suggested before diving in and working on it :)
