### ISSUE TITLE
Feature Request: Ticket "Response Time" Stats

### ISSUE THREAD

**Issue by olliebennett** [helpyio/helpy#105]
It'd be really useful to see your average (median) "first response" time to tickets. This is something that could be displayed for the last 7 days, 30 days, all time etc.

It could (if you think it's worth it) be broken down per agent.

**Comment by scott** [comment]
My original vision for all analytics was to let people leverage Google Analytics for that, but the time issue is one place where GA really doesn't do a great job with the reporting.  I also planned on a "Team" dashboard view, which would show you and your agents, how big of a queue each has, and some  other basic performance stats, which sounds pretty inline with your suggestion.

**Comment by olliebennett** [comment]
I've prepared a PR at #106 for this.

**Comment by scott** [comment]
#289
