### ISSUE TITLE
Assets for widget

### ISSUE THREAD

**Issue by rusikf** [helpyio/helpy#112]
[It looks, that there is a direct link to assets for widget.](https://github.com/helpyio/helpy/blob/master/app/assets/javascripts/widget.v1.js#L137)
But if we will use helpy in production, it will be not work because assets will be precompilled, 
We can add aditional routes for helpy, which on respond returns link to compilled version , @scott what you think about this idea?

**Comment by scott** [comment]
As long as they are not in the manifest, they should remain uncompiled. Currently tree is commented out which means you have to list the specific files you want compiled.  Although I have not tested it yet, I believe this should work.  Am I wrong?

**Comment by rusikf** [comment]
Ok, thank's, I agree with you :wink:
