### ISSUE TITLE
We're sorry, but something went wrong.  

### ISSUE THREAD

**Issue by Onderi** [helpyio/helpy#1127]
The issue has been logged for investigation. Please try again later.

when trying running on locahost

**Comment by scott** [comment]
Hi @Onderi can you please list out the exact steps you took when setting up.  Did you run `bundle exec rake db:seed`

**Comment by Onderi** [comment]
App 28613 output: Unknown ruby interpreter version (do not know how to handle): >=2.2,<3.0.
App 28613 output: /usr/lib/ruby/vendor_ruby/phusion_passenger/platform_info.rb:363: warning: Insecure world writable dir /home/deploy/.rvm/ge$
App 28613 output: Error: The application encountered the following error: Could not find rake-12.3.2 in any of the sources (Bundler::GemNotFo$
App 28613 output:

**Comment by Onderi** [comment]
I followed the exact steps [here](https://github.com/helpyio/helpy/wiki/Installing-Helpy-on-Ubuntu-18.04-with-Nginx-and-Passenger)

**Comment by Onderi** [comment]
Here is my nginx file

server{
        passenger_ruby /home/deploy/.rvm/gems/ruby-2.4.5@helpy/wrappers/ruby;

        listen 81;

        server_name sbsit.ac.ke;

        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

        root /home/deploy/helpy/public;
        passenger_enabled on;
        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }

            # pass PHP scripts to FastCGI server
        #
        #location ~ \.php$ {
        #       include snippets/fastcgi-php.conf;
        #
        #       # With php-fpm (or other unix sockets):
        #       fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
        #       # With php-cgi (or other tcp sockets):
        #       fastcgi_pass 127.0.0.1:9000;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #       deny all;
        #}
}

**Comment by scott** [comment]
Make sure you use `source /home/deploy/.rvm/scripts/rvm` when in the termninal.  If that doesn't fix it, type `which ruby` and lets see what that says.

**Comment by Onderi** [comment]
bundle exec rake db:seed gives the erroebelow

rake aborted!
NoMethodError: undefined method `paginate' for #<Class:0x0000560819e22d28>

**Comment by scott** [comment]
Hi @Onderi it seems like you are missing some dependencies, is it possible you missed one of the steps in the documentation?  I can assure you that those steps work.  Closing this issue for now, I would suggest rebuilding and making sure you don't miss anything.

**Comment by cstrock** [comment]
I'm having the same issue, and I've run through those steps 3 times.

**Comment by scott** [comment]
@cstrock sorry to hear you are running into a similar issue.  Can you add any logs (either nginx error.log or production.log)?

**Comment by cstrock** [comment]
Here is the nginx log
[error.log](https://github.com/helpyio/helpy/files/3532203/error.log)
