### ISSUE TITLE
Resolving/Closing ticket notification blocks menu action 

### ISSUE THREAD

**Issue by tvarsis** [helpyio/helpy#1157]
To reproduce: 

1. Go into an open case
2. Select the status drop down and set the case to "Mark as closed/resolved"
3. Now a notification will be show and while this notification is open/showing, it is not possible to click the "Inbox" button in the top menu, so the user will have to either wait for it to close, or manually close it to be able to use the menu again.

**Comment by scott** [comment]
@tvarsis I believe this was resolved by https://github.com/helpyio/helpy/pull/1089 . Please reopen if I am confused.
