### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by Sarke** [helpyio/helpy#1159]
Idle memory usage of 750MB+.  This seems unreasonably high for an idle clean install with nothing on it.

```
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
    1 helpyus+  20   0  361576 176848   1740 S  0.0  8.7   0:23.97 unicorn master -E production -c config/unicorn.rb -l0.0.0.0:8080
  117 helpyus+  20   0  571052 290080   3036 S  0.0 14.2   0:32.10 unicorn worker[0] -E production -c config/unicorn.rb -l0.0.0.0:8080
  119 helpyus+  20   0  391048 205156   3072 S  0.0 10.1   0:30.24 unicorn worker[1] -E production -c config/unicorn.rb -l0.0.0.0:8080
  122 helpyus+  20   0  704660 248708   3200 S  0.0 12.2   0:31.69 unicorn worker[2] -E production -c config/unicorn.rb -l0.0.0.0:8080
```

Any way to reduce this usage, or perhaps reduce the number of workers?

**Comment by scott** [comment]
You can reduce the number of workers in `config/unicorn.rb` on this line:
```
worker_processes 3
```
They will take less memory if you configure a Sidekiq process to do jobs but that will in turn take about the same amount of memory.  There are some optimizations that will be merged into master soon which may reduce the footprint somewhat.
