### ISSUE TITLE
Sign up with github is broken

### ISSUE THREAD

**Issue by goodniceweb** [helpyio/helpy#126]
Steps to reproduce:
1) Go to http://demo.helpy.io/
2) Click "Sign In"
3) In opened popup click "Sign in with github"
4) See regular error "We're sorry, but something went wrong." and url looks like that: http://demo.helpy.io/users/auth/github/callback?code=blahblahblah

**Comment by scott** [comment]
Thanks!  It was working....

**Comment by scott** [comment]
Hmmm just tried it and it worked fine for me.  I wonder why it didn't work for you.  If anyone else runs into this, please post here!

**Comment by andela-ysanni** [comment]
I got an error too.
