### ISSUE TITLE
Docker installation problem, 502 Bad Gateway.

### ISSUE THREAD

**Issue by DoTheEvo** [helpyio/helpy#1264]
Wanted to try helpy, here are the steps I took.

* in my home I did `git clone https://github.com/helpyio/helpy.git`
* I copy/paste the `~/helpy/docker\.env.sample` in to the same directory and renamed it to just `.env`
* I did not edit it, since only passphrase seemed to be needed
* I checked `~/helpy/docker/Caddyfile` but dont see anything I should be changing
* I run `docker-compose up -d` in `~/helpy/docker` and everything seems to start up, but I only get `502 Bad Gateway` when I visit `http://localhost/`

The containers are up, dont seem to be restarting, [here is look](https://i.imgur.com/z6BEvVz.png) in portainer

The problematic container seems to be helpy_helpy, which has this in its log

<details><summary>log output</summary>
<p>

    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require',
    /opt/helpy-bundle/gems/themes_on_rails-0.4.0/lib/themes_on_rails.rb:2:in `<top (required)>',
    /usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:81:in `require',
    /usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:81:in `block (2 levels) in require',
    /usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `each',
    /usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `block in require',
    /usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `each',
    /usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `require',
    /usr/local/lib/ruby/site_ruby/2.4.0/bundler.rb:114:in `require',
    /helpy/config/application.rb:8:in `<top (required)>',
    /helpy/Rakefile:4:in `require',
    /helpy/Rakefile:4:in `<top (required)>',
    /opt/helpy-bundle/gems/rake-12.3.2/lib/rake/rake_module.rb:29:in `load',
    /opt/helpy-bundle/gems/rake-12.3.2/lib/rake/rake_module.rb:29:in `load_rakefile',
    /opt/helpy-bundle/gems/rake-12.3.2/lib/rake/application.rb:703:in `raw_load_rakefile',
    /opt/helpy-bundle/gems/rake-12.3.2/lib/rake/application.rb:104:in `block in load_rakefile',
    /opt/helpy-bundle/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling',
    /opt/helpy-bundle/gems/rake-12.3.2/lib/rake/application.rb:103:in `load_rakefile',
    /opt/helpy-bundle/gems/rake-12.3.2/lib/rake/application.rb:82:in `block in run',
    /opt/helpy-bundle/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling',
    /opt/helpy-bundle/gems/rake-12.3.2/lib/rake/application.rb:80:in `run',
    /opt/helpy-bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>',
    /opt/helpy-bundle/bin/rake:23:in `load',
    /opt/helpy-bundle/bin/rake:23:in `<top (required)>',
    /usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:74:in `load',
    /usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:74:in `kernel_load',
    /usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run',
    /usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:463:in `exec',
    /usr/local/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run',
    /usr/local/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command',
    /usr/local/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch',
    /usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch',
    /usr/local/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start',
    /usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start',
    /usr/local/bin/bundle:30:in `block in <main>',
    /usr/local/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:124:in `with_friendly_errors',
    /usr/local/bin/bundle:22:in `<main>',
    Bundler Error Backtrace:,
    /helpy/config/application.rb:8:in `<top (required)>',
    /helpy/Rakefile:4:in `require',
    /helpy/Rakefile:4:in `<top (required)>',
    /opt/helpy-bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>',
    /usr/local/bin/bundle:30:in `block in <main>',
    /usr/local/bin/bundle:22:in `<main>',
    ,
    Caused by:,
    HOME environment variable (or HOMEDRIVE and HOMEPATH) must be set and point to a directory,
    /opt/helpy-bundle/gems/rb-readline-0.5.5/lib/rbreadline.rb:1097:in `<module:RbReadline>',
    /opt/helpy-bundle/gems/rb-readline-0.5.5/lib/rbreadline.rb:17:in `<top (required)>',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require',
    /opt/helpy-bundle/gems/rb-readline-0.5.5/lib/readline.rb:10:in `<module:Readline>',
    /opt/helpy-bundle/gems/rb-readline-0.5.5/lib/readline.rb:8:in `<top (required)>',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require',
    /opt/helpy-bundle/gems/thor-0.20.3/lib/thor/line_editor/readline.rb:2:in `<top (required)>',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require',
    /opt/helpy-bundle/gems/thor-0.20.3/lib/thor/line_editor.rb:2:in `<top (required)>',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require',
    /opt/helpy-bundle/gems/thor-0.20.3/lib/thor/base.rb:8:in `<top (required)>',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require',
    /opt/helpy-bundle/gems/thor-0.20.3/lib/thor/group.rb:1:in `<top (required)>',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require',
    /opt/helpy-bundle/gems/railties-4.2.11.1/lib/rails/generators.rb:4:in `<top (required)>',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require',
    /opt/helpy-bundle/gems/themes_on_rails-0.4.0/lib/themes_on_rails/engine.rb:1:in `<top (required)>',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency',
    /opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require',
    /opt/helpy-bundle/gems/themes_on_rails-0.4.0/lib/themes_on_rails.rb:2:in `<top (required)>',
    /helpy/config/application.rb:8:in `<top (required)>',
    /helpy/Rakefile:4:in `require',
    /helpy/Rakefile:4:in `<top (required)>',
    /opt/helpy-bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>',
    /usr/local/bin/bundle:30:in `block in <main>',
    /usr/local/bin/bundle:22:in `<main>',
    (See full trace by running task with --trace),
    
</p>
</details>

If I exec inside to it it either tells me its restarting, or works only for few seconds.
Since there is this in the log: `HOME environment variable (or HOMEDRIVE and HOMEPATH) must be set and point to a directory,`
I checked environmental variable for home with `printenv` and it is set to `HOME=/home/helpyuser`, but it indeed does not exist. But when [googling](https://github.com/helpyio/helpy/issues/645) it seems like its just something in the logs and should not impede the operation.

<details><summary>printenv</summary>
<p>

    helpyuser@eded17557e0c:/helpy$ printenv
    RUBYGEMS_VERSION=3.0.3
    HOSTNAME=eded17557e0c
    RUBY_VERSION=2.4.6
    GEM_HOME=/usr/local/bundle
    HELPY_USER=helpyuser
    REMOTE_STORAGE=false
    HELPY_HOME=/helpy
    PWD=/helpy
    HELPY_SLACK_INTEGRATION_ENABLED=true
    HOME=/home/helpyuser
    BUNDLE_PATH=/opt/helpy-bundle
    POSTGRES_PORT=5432
    POSTGRES_DB=helpy_production
    BUNDLE_APP_CONFIG=/usr/local/bundle
    RAILS_ENV=production
    TERM=xterm
    BUNDLE_SILENCE_ROOT_WARNING=1
    RUBY_MAJOR=2.4
    POSTGRES_PASSWORD=some_secure_pg_password_change_in_production
    POSTGRES_USER=helpy
    SHLVL=1
    RUBY_DOWNLOAD_SHA256=25da31b9815bfa9bba9f9b793c055a40a35c43c6adfb1fdbd81a09099f9b529c
    PATH=/usr/local/bundle/bin:/usr/local/bundle/gems/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    POSTGRES_HOST=postgres
    SECRET_KEY_BASE=some_secret_key_base_change_in_production
    _=/usr/bin/printenv

</p>
</details>

Any ideas?

**Comment by scott** [comment]
There is a bug that is preventing `master` or `2.4.x` from running in docker.  See #1250 If you specify to run a previous version it should work correctly.

**Comment by DoTheEvo** [comment]
Can confirm that the fix done in that other issue fixed this and the latest git pull works for me.
Thanks.

**Comment by jdiaz85** [comment]
I have the same problem with version 2.8 (master). Any solution?
