### ISSUE TITLE
Multiple translations for one language

### ISSUE THREAD

**Issue by ubergesundheit** [helpyio/helpy#127]
Hi,

I am wondering if the system can handle multiple translations for one langage? For example in german, one can use the formal way ('Sie') or personal ('Du').
If this is possible, I can create the neccesary file for the personal way.

Cheers,
ubergesundheit

**Comment by scott** [comment]
Rails give you the ability to create any locale type you want... such as formal or personal, or 'pirate' or any other dialect.  However, I don't think browsers understand the difference and to them German is German.  So you could create a personal file and a formal file, and they would be an option, but to have Helpy use it automatically in German areas, you might have to choose one or the other.

**Comment by ubergesundheit** [comment]
Ok,
what I actually want is: German admins should be able to either select "Formal German (Sie)" or "Personal German (Du)".

I will try out what is possible and will report back!

**Comment by scott** [comment]
Okay sounds good!  I am not sure how to do that without choosing from the two files, say `formal.de.yml` and `personal.de.yml` and renaming it to just `de.yml` (or creating a link).  That being said, there may be a way to do it.

**Comment by ubergesundheit** [comment]
After looking around in the code, I think the easiest method is to manually replace the strings in the `de.yml`
Otherwise, at least two new i18n keys have to be introduced. `short_name` for the language selector on the main navigation and `long_name` for usage in the admin area to differentiate German (Personal) and German (Formal)

Also, my ruby is probably too rusty to write up a patch...
