### ISSUE TITLE
Custom ticket form fields in open source edition?

### ISSUE THREAD

**Issue by floriandammeyer** [helpyio/helpy#1299]
We are evaluating a lot of self-hosted open source help desk systems at the moment. The single most important feature to us is the ability to extend the ticket form with custom form fields, because we need to know some additional information about the customer to be able to help.

In the demo of Helpy you can add custom form fields under "Ticketing Settings" (also see https://support.helpy.io/en/docs/116-customizing-ticket-forms) in the system configuration area. So that looked very promising. But after installing the open source edition on our own test servers we were disappointed to see that this feature was gone.

I couldn't find any further information about this feature besides #19 which hasn't had any real activity for a few years.

Will there be a feature for custom ticket form fields in the open source edition or is this feature reserved for the paid edition?

**Comment by scott** [comment]
Hi @floriandammeyer!  This feature is available in our paid cloud edition, available through our hosted version or you can run it on-premise with a modest financial contribution (see our Patreon.) . It is fairly trivial to add custom fields to the ticket form by hacking the open source code, which is one of the reasons the UI tool is considered a pro feature.
