### ISSUE TITLE
When changing ticket, left list disappears

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#1311]
When on the ticket view, if you change the status of the ticket, the left menu listing of tickets disappears.

**Comment by Danielshow** [comment]
Please, is this tickets been worked on?

**Comment by scott** [comment]
Yes, this is a regression in the latest master commit because of some refactoring I was doing.

**Comment by Danielshow** [comment]
Ok, that's good. Still looking for a ticket to contribute to
