### ISSUE TITLE
RailsSettings::CachedSettings is deprecated and it will removed in 0.7.0. Please use RailsSettings::Base instead. 

### ISSUE THREAD

**Issue by CPR43** [helpyio/helpy#134]
Got this issue while setting up helpy.io on puma with ruby 2.2.4

here is the log : 

*** SIGUSR2 not implemented, signal based restart unavailable!
*** SIGUSR1 not implemented, signal based restart unavailable!
*** SIGHUP not implemented, signal based logs reopening unavailable!
Puma starting in single mode...
* Version 3.4.0 (ruby 2.2.4-p230), codename: Owl Bowl Brawl
* Min threads: 0, max threads: 16
* Environment: test
DEPRECATION WARNING: RailsSettings::CachedSettings is deprecated and it will removed in 0.7.0. Please use RailsSettings::Base instead.
! Unable to load application: NoMethodError: undefined method `[]=' for nil:NilClass
C:/inetpub/wwwroot/rails/helpy-master/config/initializers/default_settings.rb:3:in `<top (required)>': undefined method `[]=' for nil:NilClass (NoMethodError)
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:652:in `block in load_config_initializer'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:651:in `load_config_initializer'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `each'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `block in <class:Engine>'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `each'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:413:in `call'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
	from C:/inetpub/wwwroot/rails/helpy-master/config/environment.rb:5:in `<top (required)>'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from config.ru:3:in `block in <main>'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/puma-3.4.0/lib/puma/configuration.rb:313:in `load_rackup'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/puma-3.4.0/lib/puma/configuration.rb:242:in `app'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/puma-3.4.0/lib/puma/runner.rb:123:in `load_and_bind'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/puma-3.4.0/lib/puma/single.rb:84:in `run'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/puma-3.4.0/lib/puma/launcher.rb:172:in `run'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/puma-3.4.0/lib/puma/cli.rb:74:in `run'
	from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/puma-3.4.0/bin/puma:10:in `<top (required)>'
	from C:/RailsInstaller/Ruby2.2.0/bin/puma:23:in `load'
	from C:/RailsInstaller/Ruby2.2.0/bin/puma:23:in `<main>'

**Comment by scott** [comment]
Can you post your puma config files so I can try to recreate the issue?  It is not clear, did you get it to run?

**Comment by CPR43** [comment]
The issue got resolved when  I changed Appsetting.defaults["Key"] to AppSetting["Key"] in default_settings.rb . Its seems _.default_ property is no longer supported in rails -4.2.6 . Thank you for creating such a great help desk system . It's working really well now .

**Comment by TechRsch** [comment]
I just cloned this gem and found that I had to make both the changes documented here.  That is to change CachedSettings  to Base to eliminate the deprecation warning.  And, more importantly, to update default_settings.rb to change Appsetting.defaults["Key"] to AppSetting["Key"].  Without that change, it failed as documented above.  This occurred with Unicorn and I have not changed its configuration.  I will attach the Gemfile, though the same issues occurred when I pushed it to Heroku.
[Gemfile.txt](https://github.com/helpyio/helpy/files/353420/Gemfile.txt)

**Comment by scott** [comment]
Another way to resolve this is to move the version back like this.  In fact I am going to push this up to master today to resolve this for now.  We still need to do some work to support the newer versions of this gem.

`gem "rails-settings-cached", '~> 0.5'`
