### ISSUE TITLE
Translate Pt-BR

### ISSUE THREAD

**Issue by felipewmartins** [helpyio/helpy#135]
Hi Scott,
 I would like translate the project to portuguese(Brazilian). 
What do you think?

**Comment by scott** [comment]
I think that would be AWESOME.  There are a lot of Brazilians that would be happy :)  Currently there is a Portuguese yml file but it is Portugal so I imagine not all the words are the same.

**Comment by felipewmartins** [comment]
Very Good :+1: 
I will send a PR with this improvement. :)
