### ISSUE TITLE
frontend driver failed 443 already in use

### ISSUE THREAD

**Issue by Kyon147** [helpyio/helpy#1383]
Hi all,

Installed via docker but when I try and run it, this error happens.

`ERROR: for frontend  Cannot start service frontend: driver failed programming external connectivity on endpoint helpy_frontend_1 (b324041aa366566ee81c40607031e72dad8af95fce46df22c80f39fc3f6f38bd): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use
`

Running this on a server where a website is also running on 443, so I need to be able to change where Helpy runs on 443 if possible.

**Comment by scott** [comment]
Hi @Kyon147 Did you try changing the port mapping in `docker-compose.yml`?

This ->
```
    ports:
      - "80:80"
      - "443:443"
```

**Comment by scott** [comment]
Please let us know if this worked.  Closing for now!
