### ISSUE TITLE
Mail processor doesn't exist

### ISSUE THREAD

**Issue by danblah** [helpyio/helpy#139]
Super excited about this project. Thanks for it and apologies if I'm missing something silly. Just deployed 0.9.2-5-g4da5c35 and all is well, having fun but I can't seem to get the mail processor to link. https://help.opentech.fund/email_processor seems to be a dead page. I saw a previous issue where they found the solution but didnt post it. Any love?

I've enabled mailgun in settings.yml and in the admin interface. Sending mail through the SMTP is working.

**Comment by scott** [comment]
That url only will respond to a POST request.  Have you tried testing your webhook in Mailgun yet?

**Comment by danblah** [comment]
Aannnnnnd I got it. Thanks for pointing me in the right direction :)
