### ISSUE TITLE
Can't enable Webhooks

### ISSUE THREAD

**Issue by nilst82** [helpyio/helpy#1429]
I do not seem to be able to enable webhooks. I'm using the 30 sec install DO image. 

It's not working on our production installation, I've just set up a new droplet ran all the updates and still no dice.

What happens?:

When I enable webhooks I get no error. When I save the settings webhooks shows as disabled again.

![Screenshot 2019-09-12 at 12 24 22](https://user-images.githubusercontent.com/6095199/64776325-4603c000-d558-11e9-9542-f22454a0f78a.png)

**Comment by scott** [comment]
Hi @nilst82 thanks for the report.  I wonder if there is a bug that is preventing it from being saved.  You can also turn this one using the API (see the Settings endpoints).
