### ISSUE TITLE
Site url issue on installation (missing scheme)

### ISSUE THREAD

**Issue by pjrobertson** [helpyio/helpy#1535]
Steps to reproduce:

1. Install new install of Helpy
2. In the onboarding screens, for the 'Site Url' field, enter your domain without a scheme (e.g. `example.com`)
3. After installation, go to Settings → General and edit some settings (e.g.  change the site name)
4. Click 'Save Settings'
5. Note the error on the top of the page "The given url is invalid"

You can fix this error by inserting a scheme (e.g. `https://` or `http://`) Site URL field on that settings page. Suggested solutions:

1. Improve the message 'The given url is invalid'. Change to 'The Site URL entered is invalid. Ensure you also enter the URL scheme (e.g http:// or https://)'
2. In the onboarding screen, validate the field to ensure a scheme is entered (if a scheme isn't entered show an error saying "please enter your URL scheme (e.g. http or https)
3. In the onboarding screen use a placeholder text that contains a scheme (to give people a hing) For example, use a placeholder: `e.g. https://www.example.com`

Edit: I actually spent hours debugging this issue because I thought it was a reverse proxy (`proxy_host`) problem with my upstream NGINX proxy. Turns out it was as simple as adding a https to the url!

**Comment by scott** [comment]
Thanks for submitting this @pjrobertson

**Comment by pjrobertson** [comment]
No problem, glad to help (a tiny amount) to making this awesome OS platform a little bit better! Sorry I don't have the time to submit the patch myself.
