### ISSUE TITLE
The more link on the QNA view is not working

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#156]
See image, it should expand the text:

![screen shot 2016-05-17 at 10 07 50 am](https://cloud.githubusercontent.com/assets/14369/15329935/e159667a-1c17-11e6-92b8-4cf25f3be5eb.png)

**Comment by jprberlin** [comment]
Wasn't this solved by a PR?

**Comment by scott** [comment]
Yes you are right, the issue did not automatically close, so closing it now....
