### ISSUE TITLE
Install Helpy in Windows using Laragon

### ISSUE THREAD

**Issue by chazkame** [helpyio/helpy#1616]
Hi,

I tried installing Helpy in a Windows Server using Laragon. I have installed ruby, rails and the dependencies, but when I tried installing Helpy, it stucks telling me that I dont have ruby installed.
Can someone help me with this issue please?

Many thanks in advance

![image](https://user-images.githubusercontent.com/38876822/73894231-cb489200-48b6-11ea-9361-e7906a6585a4.png)

**Comment by scott** [comment]
Hi @chazkame it would be great if you would let us know if you ever got this working.  You might also post this to StackOverflow.
