### ISSUE TITLE
Need attachments access in view

### ISSUE THREAD

**Issue by crcinf** [helpyio/helpy#165]
Hi scott,

I have one question.

when any user create new topic its generate a ticket and in admin view show me a message text of email send to me with attachments, but i dont get attachments access. There is a one form to do this?

Thanks in advance.

**Comment by scott** [comment]
Currently the attachment feature is limited to image files and pdf, so they can display in the browser window.  Just to make sure I understand, you are thinking there should also be a list of files in the admin view to be downloaded.  Ideally this would encompass other file formats as well, if they were supported?

**Comment by crcinf** [comment]
but in test here dont show the pdf file in the topic in admin. the email_processor dont proccess the attachments send via incoming email via hook ulr post json by postmark service...

**Comment by crcinf** [comment]
i understand that you explication, in my test here uploaded pdf or jpg working in view how do help you? but when send email via browser dont show in view admin below question user did in ticket.

**Comment by crcinf** [comment]
example in  view: in the file _thumbnail.html.rb load attachment done via button choose by users, but send file via email dont load in the thumbnail.

**Comment by scott** [comment]
Yes currently it does not pick up attachments from email.

**Comment by crcinf** [comment]
and how i add this feature?

**Comment by scott** [comment]
Hi @crcinf sorry for the slow reply.  It would take some work for sure.  I would start by looking at the documentation for Griddler and see if there is a way to grab the attachments and then feed them straight to cloudinary or S3.  Can you help with this?

**Comment by crcinf** [comment]
hi @scott, i am so glad for your attention, i am sure that is the path to the success(griddler), so i did search too in the documentation of gem griddler-postmark, but my knowledge in rails are yet so bad, but i hope when you would can develop this feature.

**Comment by scott** [comment]
This was implemented some time ago, so closing the thread
