### ISSUE TITLE
mysql support

### ISSUE THREAD

**Issue by celevra** [helpyio/helpy#166]
Hi,

thank you for the great product!
will there be mysql in the near future?

regards

celevra

**Comment by scott** [comment]
Hi @celevra at this point Helpy makes use of full text search from postgres, so adding support for mysql is not going to be super easy- it will require some changes... if someone wants to go ahead and do this work I would support it, but its not on my roadmap at this point.  Probably someday though.

**Comment by raykai** [comment]
i would love seeing support for mysql
