### ISSUE TITLE
Refactor forms to use client side validations

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#169]
Many forms on the site could be improved by implementing client side validations.  This can be done fairly easily using the `client_side_validations` gem, although on Helpy forms currently use the `bootstrap_form` gem, for which there is no adapter.

This gives two options- write the adapter for the bootstrap forms gem, or switch it out for the `simple_form` gem where needed.  I have made this change on the `admin/topics/new` form already and think its the right long term strategy since it has a nicer DSL.  Here are the forms that I know need to be refactored:

On the admin site:
`/admin/categories/:id/edit`
`/admin/categories/new`
`/admin/docs/:id/edit`
`/admin/docs/new`
`/admin/forums/:id/edit`
`/admin/forums/new`

On the main site:
`/en/topics/new`
`/en/users/edit`
`/en/users/sign_up`

There may be others, but any post type form with just one field does not need to be included since there is really no need for validations.

**Comment by shaktik1989** [comment]
I havev added a https://github.com/helpyio/helpy/pull/173 PR regarding this. Please review.
