### ISSUE TITLE
Docker Installation problem

### ISSUE THREAD

**Issue by jdiaz85** [helpyio/helpy#1706]
I have downloaded the project, created the .env and when I try to access it gives me this error:
helpy_1     | `/home/helpyuser` is not a directory.
helpy_1     | Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.

I see the same problem before:
https://github.com/helpyio/helpy/issues/1264

**Comment by bieronym** [comment]
I think it just take time for the first time to open. I have the same logs and I got 502 for the first 5 minutes.

**Comment by jdiaz85** [comment]
Thanks!
