### ISSUE TITLE
Using Docker: Caddy is stuck restarting?

### ISSUE THREAD

**Issue by floriandammeyer** [helpyio/helpy#1926]
I wanted to set up a test instance of helpy using the Docker instructions on an Ubuntu 20 server. My first problem was the incompatibility of one of the dependencies with Ruby 2.4, which I solved the same way that PR #1825 solves it.

Now I can use `docker-compose build` without errors and `docker-compose up -d` starts the containers, but I cannot access helpy. A test using `curl localhost` resulst in `curl: (7) Failed to connect to localhost port 80: Connection refused`. 

Using `docker ps` I get this result:

    CONTAINER ID   IMAGE            COMMAND                  CREATED         STATUS                          PORTS      NAMES
    15b12aa5871b   webwurst/caddy   "caddy -conf /etc/ca…"   7 minutes ago   Restarting (2) 51 seconds ago              helpy_frontend_1
    56c34f69f860   helpy_helpy      "/bin/bash /helpy/do…"   7 minutes ago   Up 7 minutes                               helpy_helpy_1
    35a46af96e58   postgres:9.4     "docker-entrypoint.s…"   7 minutes ago   Up 7 minutes                    5432/tcp   helpy_postgres_1

So it seems like Caddy is stuck restarting. I did not change anything in the files `docker/.env` and `docker/Caddyfile` because it didn't seem to be necessary.

Do I just have to wait for a while or is there another fix?

## UPDATE
I realized that the used version of Caddy is ancient (the docker image `webwurst/caddy` is Caddy v0.95 or something and by now, there is Caddy v2.x). I replaced the Caddy container with an nginx proxy, using the barebones configuration from here for now: https://support.helpy.io/en/docs/168-installing-your-own-helpy-pro-private-cloud-or-on-premises-instance I may update the configuration to resemble the Caddyfile more in the future, but with nginx, it's working fine.

**Comment by kimadactyl** [comment]
I have the same issue. Alternative solution: in `docker-compose.yml` change `webwurst/caddy` to `webwurst/caddy:0.9-beta.1`. Then rerun `docker-compose up -d` and it runs for me.

**Comment by lazyest** [comment]
I've mostly managed to run docker version with recent Caddy excepts of new fire_server concept. Now its working mostly but not the avatars(and other attaches I suppose). Maybe someone is more familar with Caddy? I'm trying 
  root * /helpy/public
  file_server /assets 
  file_server /uploads

but no luck :(

**Comment by lazyest** [comment]
anyhow
I've managed to do it
The idea was to modify original Caddyfile with some sed so Caddyfile is very similar to repo's one
example is below:

my_hostname:443 {
  #tls off
  root * /helpy/public
  file_server /uploads/
  @site {  not path /uploads/* }

  header /assets {
    gzip
    Expires "Thu, 31 Dec 2037 23:55:55 GMT"
    Cache-Control public
  }

  header /uploads

  reverse_proxy @site helpy:8080 {
    #except /assets
    #except /uploads
    header_up Host {host}
    header_up X-Real-IP {remote}
    header_up X-Forwarded-Proto {scheme}
  }
  log stdout
 
}
