### ISSUE TITLE
Elements and thread missing when submitting internal note

### ISSUE THREAD

**Issue by JonathanKryza** [helpyio/helpy#205]
After submitting an internal note, the original thread/message is not accessible. Also, the dropdown menu is blocked by the element below. (See gif)

https://dl.dropboxusercontent.com/u/1746820/Helpy_InternalNote.gif

Firefox 47.0.0

**Comment by scott** [comment]
Thanks for providing this report!  I am aware of the dropdown menu issue if the content of the post is too small.  The other one is not something I am familiar with and will look into.

**Comment by scott** [comment]
By the way, what software/tool did you use to create that .gif?

**Comment by JonathanKryza** [comment]
https://github.com/justinfrankel/licecap

**Comment by scott** [comment]
I have not been able to reproduce the disappearing thread bug, can you send a nifty gif of what you are seeing?

**Comment by JonathanKryza** [comment]
It seems that it only happens with the discussion #2 - About Helpy.

#1 and the test discussion I started acts correctly(collapsible message
thread).

https://dl.dropboxusercontent.com/u/1746820/Discussions.gif

It may just be an issue with that particular discussion thread.




-Jonathan Kryza

**Comment by scott** [comment]
Okay I figured it out.  You actually click on a different ticket in the video you showed, which gives the appearance of the thread disappearing.  However, there is still a problem with one of the "filler" messages- #2 does not have an original message, it is only a reply which is an error in the way it is generated.

So bottom line, the underlying system is fine, the bug exists in the sample message generated for the hosted version.  I will fix that.

**Comment by scott** [comment]
This should now be fixed on new accounts.
