### ISSUE TITLE
Contact | Security Issues

### ISSUE THREAD

**Issue by ghost** [helpyio/helpy#2063]
Dear helpy contributors,

I've tried to contact you through the email provided in the security policy, but got no response.
Please get back to me at: vulnerability@whitesourcesoftware.com.
It's about security issues found in your project.

Thanks,
Miriam

**Comment by scott** [comment]
Hi Miriam, thanks for reaching out via our email.  Our disclosure policy is outlined here: https://github.com/helpyio/helpy/blob/master/SECURITY.md
