### ISSUE TITLE
Support pasting an image from clipboard

### ISSUE THREAD

**Issue by pilap82** [helpyio/helpy#218]
If I have an image in my clipboard and paste it in the Trix editor, it will be displayed but not saved.

Is that expected? If so is there any plan to persist images added this way?

Thanks, Pierre

**Comment by scott** [comment]
Thanks for reporting this.  It does not sound like the intended behavior.

**Comment by skatkov** [comment]
I time to looks into this. There are two ways to go with this:
- disable this feature in trix
- or configure it to work with cloudinary

As far as i understand, second option is prefered. So i'm looking into cloudinary codebase for now, never worked with it before.

**Comment by scott** [comment]
Yes, take a look at attachinary as well, we make use of that for drag and drop uploading.

**Comment by scott** [comment]
@skatkov Any updates on this?

**Comment by scott** [comment]
We have moved to the summernote editor which supports this.
