### ISSUE TITLE
Remove "RandomUser.me" API calls

### ISSUE THREAD

**Issue by olliebennett** [helpyio/helpy#226]
This seems like an unnecessary gem, and a possible point of failure in the `seeds.rb` file. It seems that's the only place it's used. Given we already use the `faker` gem, would you be okay with removing the `ruser` gem dependency?

Note: Since #30 I know it's no longer such a heavy dependency, but think it's worth deleting anyway.

**Comment by scott** [comment]
I don't think this is used in the `seeds.rb` file, am I wrong?  It is used in `populate.rb` where it is definitely not mission critical, but needed to create the fake data used on the demo site.
