### ISSUE TITLE
right-to-left language support

### ISSUE THREAD

**Issue by hadifarnoud** [helpyio/helpy#227]
does helpy support RTL? if so, I can add Persian translation.

**Comment by hadifarnoud** [comment]
if someone explain in details how can I add RTL support myself (like checking for language and if it's RTL load certain css file or load certain email templates), I can add RTL support too

**Comment by scott** [comment]
Hi @hadifarnoud it does not support it currently but it definitely should.  I will try to look into the details of how to do it and update this thread.  If anyone else has experience with this, any help would be appreciated.

**Comment by hadifarnoud** [comment]
you can count on me for templates and css edits and test. if you sort out how you add styles/change templates in the app, I can do the rest.

**Comment by scott** [comment]
Okay give me a few days to start checking into it.  I have a couple questions for you- Helpy makes use of some center aligned text- how is this handled in RTL?  Just curious...

**Comment by hadifarnoud** [comment]
it's not only the alignment of text. if you mix the English and Arabic, the text would mix up. the solution is `direction: rtl` in css. that changes the direction of the text and help fix the issue.

for doing a proper RTL support. the styling must be in a separate css file (like rtl.css) and load it if language is set to Arabic/Persian for example.

for email templates, I think we can have a separate HTML files for RTL because styles have to be embedded inside the HTML.

**Comment by scott** [comment]
Okay this sounds fairly easy then.  Helpy looks at a URL param to determine what language to use, so it sounds like we could just switch the CSS using that if there is not a more elegant way.  The only tricky area is themes.  Helpy also supports multiple themes, which have their own CSS sheets, so we would need to be clear about which themes support RTL and which do not...

**Comment by scott** [comment]
I also found this [https://github.com/morteza/bootstrap-rtl](https://github.com/morteza/bootstrap-rtl) for bootstrap which should help with the CSS, since most of Helpy uses fairly standard bootstrap CSS

**Comment by hadifarnoud** [comment]
sounds good scott. what about email templates? they need to be RTL too.

would you push this so I can get on adding more RTL style to fix Helpy default theme?

**Comment by scott** [comment]
Great work on the translation!  I have added a branch/pr that includes the beginnings of the RTL support, and actually it seems to have gotten farther than I expected.  See #249

**Comment by scott** [comment]
I commented this and a few other things in the PR, but this will give you an idea of what it looks like, in English though.

![screen shot 2016-07-21 at 8 58 27 am](https://cloud.githubusercontent.com/assets/14369/17027985/4739b740-4f23-11e6-900e-5e924c3e30b8.png)

**Comment by hadifarnoud** [comment]
this looks promising. I'll fix the remaining styling issues. btw, I think the ISO code for Persian is `fa`. I could be wrong though

**Comment by scott** [comment]
Yes, notably I see the upper header should be reversed, and some other spacing.  I looked at the email templates too, I am guessing the text templates will just work.  The html templates will probably need a style change to get them going RTL although even there I am not sure, I think it may depend on how the email client interprets it.  The text strings are just in standard `<p>` tags.
