### ISSUE TITLE
LDAP integration

### ISSUE THREAD

**Issue by zefanja** [helpyio/helpy#24]
This is maybe a long term goal, but it would be nice to have an LDAP connector so you can use it in your existing AD/LDAP infrastructure.

**Comment by Vad1mo** [comment]
I am also interested in this feature. Helpy is using Omniauth that has LDAP support https://github.com/intridea/omniauth-ldap

I am not an Ruby expert but, I surly can help out writing and testing something with AD and JumpCloud.

**Comment by gdeflaux** [comment]
+1 on LDAP support

**Comment by gerickt** [comment]
+1

**Comment by scott** [comment]
This is now available in our commercial version, so closing it here.

**Comment by jdaviescoates** [comment]
@scott it is possible to use LDAP using a self-hosted open source instance? e.g. perhaps by buying an upgrade or something? thanks!
