### ISSUE TITLE
Knowledge Base - undefined response

### ISSUE THREAD

**Issue by JonathanKryza** [helpyio/helpy#268]
When answering the "Did this solve your problem?" at the bottom of an article, "undefined" pops up to the right of "GREAT!"

![screenshot 2016-08-04 at 10 04 28 am](https://cloud.githubusercontent.com/assets/3247900/17407009/58c37eac-5a2b-11e6-9d2d-771587208545.png)
![screenshot 2016-08-04 at 10 04 41 am](https://cloud.githubusercontent.com/assets/3247900/17407017/5f988484-5a2b-11e6-81ea-051015a7c4ca.png)

**Comment by scott** [comment]
Thanks Jon, that should be easy to fix.
