### ISSUE TITLE
RTL support in email templates

### ISSUE THREAD

**Issue by hadifarnoud** [helpyio/helpy#271]
We have to do RTL thing for email templates as well. should we just have a different templates for RTL languages or it's easier to add necessary inline css via a helper method?

<img width="482" alt="screen shot 1395-05-11 at 9 43 39 am" src="https://cloud.githubusercontent.com/assets/589808/17284055/8987f02e-57cc-11e6-8708-a376e34f37a9.png">

**Comment by scott** [comment]
Thats a good question.  Let me try dropping in the helper method or a similar one to switch the `p` tags to rtl.

**Comment by scott** [comment]
I got this working correctly on the regular mailers.  Still not getting RTL on the devise mailers...

**Comment by hadifarnoud** [comment]
aren't they under app/views/devise/ ? it seems like a normal html template. btw, you can add RTL styles to `<p>` tags too. just need both `direction:rtl;` and `text-align:right;`

**Comment by scott** [comment]
I think this is fixed now.  The issue was that getting the user locale to the template was not working because of the way the Devise mailer works, so I finally just created a `.fa` version of the mailer that uses `<div dir=rtl>` around the email body.  Do you think this will work reliably?

**Comment by scott** [comment]
#296

**Comment by hadifarnoud** [comment]
it should. if there is any `text-align: left;` in those templates, we should remove them too.
if text align is not set explicitly, `dir=rtl` will correctly change text direction and text align.

I'll test your PR and will comment on it if found any issue

**Comment by scott** [comment]
I merged it in just now, let me know if you see any more things that need to support RTL.
