### ISSUE TITLE
Login flash message displays twice on light and flat themes

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#278]
The login message appears twice on these two themes, which use a slightly different view for login.  See the example below:

![screen shot 2016-08-08 at 10 58 04 am](https://cloud.githubusercontent.com/assets/14369/17488539/18f7829e-5d57-11e6-943f-a4adfa5b9dbd.png)

**Comment by felipewmartins** [comment]
Hi Scott,
 This error is occurring on master branch? I could not simulate. :/
