### ISSUE TITLE
Lock Turbolinks version

### ISSUE THREAD

**Issue by connorshea** [helpyio/helpy#287]
When upgrading to Rails 5 you may end up upgrading Turbolinks to v5, which would be problematic since there are tons of breaking changes.

For now I'd recommend locking the version to `~> 2` in the Gemfile.

**Comment by scott** [comment]
Do you think for now, we should also update the gem name to reference `turbolinks-classic`?

**Comment by connorshea** [comment]
@scott I don't think turbolinks-classic is an actual gem, is it?

**Comment by Rynaro** [comment]
The `turbolinks-classics` is now deprecated, and the project team recommends to use the `turbolinks` with new flow provided by 5 version.
I think is a good solution locking the Gemfile Turbolinks version in `~> 2` for now, like the @connorshea said. And in future creating a planning to model Helpy scaffold to supports the new Turbolinks versions.

**Comment by scott** [comment]
Okay this sounds good.  Can you submit a PR @Rynaro?

**Comment by Rynaro** [comment]
Sure! I will send a PR with this modification.
