### ISSUE TITLE
Helpy needs to observe time zones

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#292]
This has never been a huge issue because of the way times are displayed in a relative form (i.e.... 30 minutes ago.)  However, with reporting #289 #106 this is an issue.  We need to collect a time zone setting for users- maybe just agents, but it might make sense to just include all users.

**Comment by olliebennett** [comment]
Sounds good. Our implementation uses the following:

```ruby
class ApplicationController < ActionController::Base
  around_action :user_time_zone, if: :current_user

  def user_time_zone(&block)
    timezone = current_user.time_zone.blank? ? 'UTC' : current_user.time_zone
    Time.use_zone(timezone, &block)
  end
end
```

**Comment by scott** [comment]
Thanks for the suggestion- looks pretty similar.  In the PR I set the default in the `User` to 'UTC' so I am not sure we need to explicitly set the variable.
