### ISSUE TITLE
Create Italian Translation

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#298]
We have i18n coverage for many languages, but one we are missing is Italian.   Would be great to get some help with this!  There is an updated guide to translation in the `locales` directory

[https://github.com/helpyio/helpy/blob/master/config/locales/translating.md](https://github.com/helpyio/helpy/blob/master/config/locales/translating.md)

**Comment by bmoree** [comment]
it's far from perfect, but i did spend a lot of time on it. Moreover, it's probably an old version, so I hope it still is of some use.
[it.zip](https://github.com/helpyio/helpy/files/464845/it.zip)
 (zipped it, because github doesn't support yml files...)

**Comment by CGA1123** [comment]
@bmoree could you create a pull request to add that file to `config/locales`

**Comment by bmoree** [comment]
@CGA1123 I have no Idea how to do that, that's why I've added the file to my comment.
Plus, it probably needs some work to fit with the current language file: we've customized our copy of helpy a few times, so it's probably gonna break when we update (still on v0.8.1-14-gb936447).

**Comment by CGA1123** [comment]
@bmoree I created a pull request to add your translations. 

However, the new strings that have been added since the version you are currently using are not yet translated (I don't know Italian, sadly).

**Comment by scott** [comment]
Thanks @bmoree for contributing this!
