### ISSUE TITLE
Upgrading Heroku "One Click Install" Helpy

### ISSUE THREAD

**Issue by brianjking** [helpyio/helpy#300]
Hi,

If I've installed using your "One click installer" on Heroku what is the upgrade process? I wasn't able to find any documentation available on this procedure.

Thanks!

**Comment by scott** [comment]
You will have to clone the heroku repo, pull and merge from github and then push it back to Heroku.  Visit your app's homepage on Heroku and navigate to the Deploy section. Follow the instructions under Heroku Git - Use Heroku Toolbelt. In particular:

```
heroku login 
heroku git:clone -a <your app name> 
cd <your app name> 
```
Once you have this set up, you can update your app with changes from the repository with the following:

```
git remote add upstream https://github.com/helpyio/helpy
git pull upstream master 
git push heroku master
```

**Comment by brianjking** [comment]
@scott Thanks. Appreciate it.

**Comment by hadifarnoud** [comment]
is there any need for migration?

**Comment by scott** [comment]
Yes I think you do have to explicitly tell Heroku to migrate on version upgrades using `heroku run rake db:migrate` if the update requires a migration.
