### ISSUE TITLE
custom SSO

### ISSUE THREAD

**Issue by hadifarnoud** [helpyio/helpy#302]
is it possible to use a custom single sign on with Helpy? it would be great if we can connect it to our own app's login

**Comment by scott** [comment]
Do you use Devise for auth?

**Comment by hadifarnoud** [comment]
On our app? No. We are not on Ruby on Rails

Hadi Farnoud

On Thu, 18 Aug 2016 at 17:46 Scott Miller

<
mailto:Scott Miller <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Do you use Devise for auth?

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/helpyio/helpy/issues/302#issuecomment-240719346
, or

**Comment by hadifarnoud** [comment]
It would be a great addition to Helpy. Customers expect to be logged in already. forcing them to sign up in yet another place may confuse them.

**Comment by scott** [comment]
Yeah I agree although it is a somewhat complicated thing.  Can your app support oauth2?

**Comment by hadifarnoud** [comment]
oauth2 will do, but I think there are better ways. I'm not sure how Zendesk works but it's very convenient.

**Comment by azul** [comment]
Helpy uses omniauth under the hood. That's a rails tool to support different authentication strategies. Here's a list of the different existing strategies:
https://github.com/omniauth/omniauth/wiki/List-of-Strategies

I wrote an omniauth strategy for our own sso solution and plugged it in and it basically just worked. If your system supports oauth2 that may be a good starting point.

**Comment by hadifarnoud** [comment]
an example would be awesome @azul.

**Comment by azul** [comment]
https://0xacab.org/riseup/helpy/commit/b1444d269ff5f6efbb83ea28a51b0053c5a028e8
Not sure this is helpful though.
You replace the other gems with your own omniauth strategy, require it in the devise initializer and add a callback in the omniauth_callbacks_controller. The other changes are specific to the strategy we use.
If you are using oath2 use one of the existing oauth2 based strategies as a sample instead.

hope this helps.

**Comment by hadifarnoud** [comment]
@azul I used your code but it turns out it only works with omniauth. this is harder than I thought and requires editing core files (which makes future updates a bit painful). do you have any plan for this @scott ?

**Comment by azul** [comment]
@hadifarnoud I think there is no way around loading your custom auth gem, requiring it and having hooks for it in your routes and maybe even the callback controller. Additions to the gemfile can occasionally lead to conflicts if they are in the same line another gem is added upstream. But usually these are straight forward to resolve. Gemfile.lock is autogenerated by running bundler so conflicts in there are easy to resolve.
I agree this increases maintainance but i don't see any shortcut.

**Comment by hadifarnoud** [comment]
@azul you may be right. I have to first figure out how to make this work. However, I think having a configurable custom Oauth2 is the way forward. most helpdesk systems have it. It may make sense to add it to Helpy.
