### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by felipewmartins** [helpyio/helpy#303]
Hi,
 When I started the helpy it was presented at the log the following message:

**DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block (2 levels) in class:Railtie at /home/felipe/.rvm/gems/ruby-2.2.1/gems/sass-rails-5.0.5/lib/sass/rails/railtie.rb:57)
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block (2 levels) in class:Railtie at /home/felipe/.rvm/gems/ruby-2.2.1/gems/sass-rails-5.0.5/lib/sass/rails/railtie.rb:57)**

Question: Can I update the sass-rails gem?

**Comment by CGA1123** [comment]
@felipewmartins 

[saas-rails 5.0.6 fixes this.](https://github.com/rails/sass-rails/pull/382)

Given that this is just a patch, updating should be fine.
