### ISSUE TITLE
Common reply parsing fail

### ISSUE THREAD

**Issue by Seven-dev** [helpyio/helpy#305]
Common reply text stops at '.
Example:
"You've been banned."
Becomes:
"You"

No client or server side errors.
It appears to be saved correctly on the server but when I reply to some discussion and choose a common reply, I'll get this bug.

**Comment by CGA1123** [comment]
Seems to me this is probably due to [this](https://github.com/helpyio/helpy/blob/252ae27129b56b1bcd59c40c528376c00a44a439/app/helpers/admin_helper.rb#L31) piece of code not escaping `'`'s?
