### ISSUE TITLE
outbound emails are send as "agents@none"

### ISSUE THREAD

**Issue by hadifarnoud** [helpyio/helpy#317]
I'm using Sendgrid and set my mail domain as kamva.ir

Sendgrid shows me the mail is from `agents@none` even though I set the email to `support@camva.ir`

update: this happens if you try to open an issue with the same email as one of your agents

**Comment by scott** [comment]
Are you on the master branch?  This is actually the notifications feature- it sends to agents@none and bcc's to each agent that has opted in to receive notifications.  Customers should still be receiving from your support address.
