### ISSUE TITLE
better file management and branding

### ISSUE THREAD

**Issue by hadifarnoud** [helpyio/helpy#318]
when installing Helpy, there is no easy way to change favicon and profile images. or there is a way but I haven't found it.

also on heroku, there is no easy way to manage uploaded files. I think helpy needs S3 integration. The process of adding images in contents could be better too. as it is now, I can't add any images to Helpy

**Comment by CGA1123** [comment]
The favicon can be changed to whatever you want it to in `/admin/settings` under 'design'

Just ensure that the file you type in in the favicon field corresponds to a file in the `APP_ROOT/assets/images`

**Comment by scott** [comment]
You can also use a remote hosted image by providing a full URL.  To enable images for your account you need to add an API key for Cloudinary.  They have a free tier that should suffice for smaller accounts.  I want do to some kind of S3 integration soon, it is definitely on the backlog.  You can see it here: [https://trello.com/b/NuiWsdmK/helpy](https://trello.com/b/NuiWsdmK/helpy)

**Comment by hadifarnoud** [comment]
Cool. S3 integration would be awesome.

**Comment by hadifarnoud** [comment]
@CGA1123 I know how to do it but UX wise, it's not so good. If you give user ability to upload the logo right in admin, that would make things simpler.
