### ISSUE TITLE
Add better CSS handling for printing of tickets, other views

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#323]
Create a stylesheet for printing.

**Comment by hin101** [comment]
I can have a look at this one for you.

**Comment by hin101** [comment]
#341 removed href links from print view

**Comment by scott** [comment]
Can you make one more enhancement to this and remove the "support pipeline" from the printable area?  I don't think this adds much value if someone is trying to print a ticket.

**Comment by hin101** [comment]
Issue fixed in #352
