### ISSUE TITLE
If Knowledgebase is only enabled component then user sign-ups should be disabled (re: #301)

### ISSUE THREAD

**Issue by brianjking** [helpyio/helpy#334]
![sign-up](https://cloud.githubusercontent.com/assets/6786817/18712976/54c13760-7fd6-11e6-8b14-12ffa9255888.png)

If a Helpy site is only using the Knowledgebase component and has disabled the other functionality the sign-up function should be disabled/removed.

- See: #301 
- https://github.com/helpyio/helpy/issues/301#issuecomment-248192069
cc: @scott 

Thanks!

**Comment by scott** [comment]
I beat you to it, see this commit https://github.com/helpyio/helpy/commit/043dba86bf0aa6d1e4fa87f9e101314027cba601

If you pull from master, you should see the changes.

**Comment by brianjking** [comment]
@scott Thanks, looks to be working! 😺

**Comment by schmurfy** [comment]
I know this issue is closed but it would be nice to have the option to disable signup altogether without making any assumptions on the user's usecase, we are currently trying out helpy and don't want anyone signup up.
