### ISSUE TITLE
Notification emails are sent out to non-agents

### ISSUE THREAD

**Issue by mrManner** [helpyio/helpy#335]
Still trying to narrow this down, but:

When receiving new topics/tickets via email, notification emails should be sent out to those agents who have enabled email notifications. Currently an email is generated and sent out to some other registered users as well - even some who haven't activated their accounts (another user having sent in an email but never set a password/used the web interface). The log from helpy states that the email was sent to "agents", in Sendgrid's log there are 10-ish recipients per email. We have 5 agents registered, and more than 10 users in total.

I'll try to understand which users receive emails and why as soon as I've set up a new test environment that looks more like production =)

**Comment by scott** [comment]
Hey thanks for posting this.  The way the notifier currently works is that it sends to a user named `agents` and then BCCs to the agents that have opted in for notifications.  So it is totally expected to see the agents@none in Sendgrids logs and they don't charge/count these against your send quota.

This has caused quite a bit of confusion so I am planning to change it, and take care of the new agent thing as well.  If you still think you are getting extra messages, it would be interesting to know why that is.

**Comment by mrManner** [comment]
Yup, the agents mail wasn't a problem - I know that some regular users ("customers" if you like) received notifications since they called me :)

Here is an excerpt from our Mailgun log:

`{
  "tags": [],
  "envelope": {
    "transport": "smtp",
    "sender": "jamboree17@scouterna.se",
    "sending-ip": "209.61.151.224",
    "targets": "anna-karin.hennig@scouterna.se"
  },
  "storage": {
    "url": "https://so.api.mailgun.net/v3/domains/jamboree.xn--st-fka.is/messages/eyJwIjpmYWxzZSwiayI6ImI4YmE2MjA3LWM0NDMtNDgxOS04NWIzLTFkN2IyYmM3ZWZjNCIsInMiOiIwY2U4MGMzNjcyIiwiYyI6InNib3JkIn0=",
    "key": "eyJwIjpmYWxzZSwiayI6ImI4YmE2MjA3LWM0NDMtNDgxOS04NWIzLTFkN2IyYmM3ZWZjNCIsInMiOiIwY2U4MGMzNjcyIiwiYyI6InNib3JkIn0="
  },
  "recipient-domain": "scouterna.se",
  "id": "qOki3WeBR9GDXguOTN_XkA",
  "campaigns": [],
  "user-variables": {},
  "flags": {
    "is-routed": false,
    "is-authenticated": true,
    "is-system-test": false,
    "is-test-mode": false
  },
  "log-level": "info",
  "timestamp": 1474539997.091805,
  "message": {
    "headers": {
      "to": "agents",
      "message-id": "57e3b1d6f137_1d5c75222e874660@wsj-icepeak.mail",
      "from": "jamboree17@scouterna.se",
      "subject": "[Jamboree17] #55-Nytt formulär Kontakta oss"
    },
    "attachments": [],
    "recipients": [
      "adam.lundberg@scouterna.se",
      "josephine.hihldor@scouterna.se",
      "jmanner@kth.se",
      "brittis_spals@hotmail.com",
      "emil.andersson@ocay.se",
      "anna-karin.hennig@scouterna.se",
      "magnus.klingnas@scouterna.se",
      "clanzer1970@aol.com",
      "info1@fancyfood.se",
      "1davewitteveen@gmail.com",
      "johan.manner@scouterna.se",
      "info@scouterna.se",
      "mimmi.henry@gmail.com",
      "admin@test.com",
      "agents@in7.ord2.postgun.com"
    ],
    "size": 2634
  },
  "recipient": "anna-karin.hennig@scouterna.se",
  "event": "delivered",
  "delivery-status": {
    "tls": true,
    "mx-host": "scouterna-se.mail.protection.outlook.com",
    "attempt-no": 1,
    "description": null,
    "session-seconds": 2.6581947803497314,
    "code": 0,
    "message": "",
    "certificate-verified": true
  }
}`

**Comment by scott** [comment]
This should be fixed now, if you pull from master.  There was in fact a bug that caused this.

**Comment by mrManner** [comment]
Thank you! I've updated and will test it tonight =)

**Comment by scott** [comment]
Thank you for reporting the issue, thats a particularly nasty one.
