### ISSUE TITLE
Flag for Review Feature

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#343]
# Overview

The community feature of Helpy allows users to create and reply to messages in an open forum and interact with each other through discussion threads.  The post flagging feature makes it possible for other users to alert forum administrators that possibly objectionable content has been created in the community, and should trigger a review by the administrators.
# Stories
1. Each post displayed in the community forums should have a tiny link that says "Flag for review".
2. The "Flag for Review" option should only work for users who are currently logged in.  If a user is not logged in, clicking on the link will prompt the user to log in.
3. When a user clicks "Flag for Review" the system should automatically create a private discussion topic that is shown as being from the user who has reported the thread. 
   a. After clicking, a modal should be shown that asks the user to add a reason for flagging the post.  This input should be included in the private discussion that is being created.
   b. The title of this discussion should be "Flagged for review: [name of the parent topic of the post that was flagged]"
   c. The body of this discussion should provide a link to the admin page for the flagged topic/post.

**Comment by CGA1123** [comment]
Allowing the user to add a reason for reporting might be a nice touch as well.

**Comment by hin101** [comment]
Hey Scott, I am working on this one for you

**Comment by scott** [comment]
I think adding a reason for reporting input is a good idea, it will also reduce the likelihood of people accidently reporting posts for no reason.  I will update the stories.

**Comment by hin101** [comment]
#349

**Comment by hin101** [comment]
1st pull request: #349
