### ISSUE TITLE
Try enable cloudinary (

### ISSUE THREAD

**Issue by kerncore** [helpyio/helpy#344]
HI, 

I'm try enable cloudinary but unsuccessful (( 

-- 
Completed 500 Internal Server Error in 1441ms (ActiveRecord: 15.8ms)

ActionView::Template::Error (Must supply cloud_name in tag or in configuration):
    19: <link href='//fonts.googleapis.com/css?family=Droid+Sans:400,700|Droid+Serif:400,700|Lobster' rel='stylesheet' type='text/css'>
    20:
    21: <%= csrf_meta_tags %>
    22: <%= favicon_link_tag "#{AppSettings['design.favicon']}" %>
    23: <%= cloudinary_js_config %>
    24:
    25: <script data-turbolinks-eval="false">
  app/views/layouts/_head.html.erb:22:in `_app_views_layouts__head_html_erb__1293142757795611720_77091400'
  app/views/layouts/admin.html.erb:5:in `_app_views_layouts_admin_html_erb___1547727761266705222_84701720'

**Comment by CGA1123** [comment]
Looks like you haven't set up cloudinary options in the admin settings.

**Comment by kerncore** [comment]
Exactly!
Thanks, ;)

**Comment by CGA1123** [comment]
@kerncore No problem!
