### ISSUE TITLE
Sparkpost rejects notifications

### ISSUE THREAD

**Issue by hvdvegt** [helpyio/helpy#347]
My agents don't receive notifications of new messages or replies. After some digging, I've found that sparkpost rejects them, probably because of the to address supplied.
{
    "bounce_class": "25",
    "error_code": "501",
    "raw_reason": "501 5.5.2 RCPT TO syntax error",
    "reason": "501 5.5.2 RCPT TO syntax error",
    "tdate": "2016-09-29T07:37:46.000Z",
    "timestamp": "2016-09-29T09:37:46.000+02:00",
    "type": "policy_rejection"
}

**Comment by scott** [comment]
Yeah it seems like it.  I only tested with Sendgrid...
