### ISSUE TITLE
Proposal for file uploads to file system instead of Cloudinary?

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#355]
Currently file uploads require the Cloudinary service to handle and host images.  This has advantages because it let us move faster in adding this feature early on (no need for imagemagick, etc.) and it works well for Heroku.  

Now though, I think it would be advantageous to support multiple options here.  If you have thoughts on this, please post them.  

One solution I am considering- have the default option be that it just uploads files to the file system that Helpy is running on, unless you specifically provide an API key for Cloudinary.  Then it would work "out of the box" for any users that self install on their own server.  For Heroku hosters they would still need to use Cloudinary, or a possible future S3 option.

Thoughts?

**Comment by connorshea** [comment]
What currently handles uploads? Paperclip, Carrierwave, something else?

**Comment by connorshea** [comment]
I believe Fog might be good for this as an adapter for multiple file hosting backends, but I'm not 100% sure.

**Comment by hadifarnoud** [comment]
upload to file system unless Cloudinary or S3 is setup. that makes sense to me
