### ISSUE TITLE
Remove multiple punctuation marks in a row (like "Still Need Help??")

### ISSUE THREAD

**Issue by rschaerer** [helpyio/helpy#372]
I came up with this in [the discussion](https://github.com/helpyio/helpy/commit/6a28bab90eabea4a8bcbebd111cc2b61013c7e27#commitcomment-19352092) with @Jcambass during the german translation imporvement:

> @Jcambass personally, I don't like multiple punctuation marks in a row. Especially when it comes down to :exclamation: -Marks, because I trust Terry Pratchett's opinion on this topic: :boom: 
> 
> > [Multiple exclamation marks are a sure sign of a diseased mind!](https://de.wikipedia.org/w/index.php?title=Terry_Pratchett&oldid=55118471#Zitate)
> 

And it seems like @Jcambass and I agree on removing multiple punctuation marks for the sake of correct grammatical spelling.

Should I change this on the other languages as well? Maybe I could do it in the same commit as #370 to prevent commit noise for linguistic changes?!?!?!!!!!111111!1!!!!!!1??!!!! :stuck_out_tongue_winking_eye:

**Comment by scott** [comment]
This is fine, it would be great if you could submit it with #370
