### ISSUE TITLE
Dropdown Menu Bug

### ISSUE THREAD

**Issue by CGA1123** [helpyio/helpy#373]
The dropdown menu is covered by over posts.

Screenshot below:

<img width="803" alt="9bc5de9af26d8f492ef5352b4b4e4445" src="https://cloud.githubusercontent.com/assets/7707413/19220472/92d6d188-8e25-11e6-8b66-94f9a9e0f70f.png">

Ideally the dropdown menu should show over the other elements.

**Comment by scott** [comment]
Yeah I know.  If you can figure out how to make it do that, go for it!  If not, another solution is to just give that container a minimum height big enough to always fit the dropdown.
