### ISSUE TITLE
first login

### ISSUE THREAD

**Issue by jakobii** [helpyio/helpy#378]
How do you login for the first time as an admin once you have built the server? the only place in the settings.yml that could possibly constitute "first time login credentials" don't seem to work. I must be totally missing something... any help/direction would be super awesome! thank you!

The settings.yml:
**admin_email: <my-email>@gmail.com
smtp_mail_username:  # Enter your SMTP email username
smtp_mail_password:  # Enter your SMTP email password**

**Comment by kwando** [comment]
This is poorly documented, using the same credentials as the demo worked for me.

See: https://github.com/helpyio/helpy#live-demo for details.

**Comment by jakobii** [comment]
@kwanda
 thanks for the tip! i just tried, no luck. the only thing I really customized was the settings.yml. I changing settings.yml to the original values, but still no luck. "Invalid email address or password."

**Comment by CGA1123** [comment]
You might need to seed the database.

rake db:seed

Sent from my iPhone

On 11 Oct 2016, at 07:21, jakobii <notifications@github.com<mailto:notifications@github.com>> wrote:


@kwanda<https://github.com/kwanda>
thanks for the tip! i just tried, no luck. the only thing I really customized was the settings.yml. I changing settings.yml to the original values, but still no luck. "Invalid email address or password."

-

**Comment by jakobii** [comment]
@CGA1123 is the first admin login  Admin User: "admin@test.com" and password: "12345678"?  I've followed both of these tutorials closely:

http://support.helpy.io/en/knowledgebase/11-installing-helpy-yourself/docs/1-installing-helpy-on-using-the-digital-ocean-rails-image

http://support.helpy.io/en/knowledgebase/11-installing-helpy-yourself/docs/27-installing-helpy-on-ubuntu-14-04-using-passenger-and-nginx

**Comment by scott** [comment]
yes, that is what you should use the first time you login.  you will go through a short onboarding that prompts you to change your password on your first time logging in.

**Comment by jakobii** [comment]
oh ok great, thanks for the confirmation! at least now I can start narrowing down what I'm doing wrong

**Comment by domosorio** [comment]
I have the same problem..."Invalid email address or password." Using User: "admin@test.com" and password: "12345678" but continúe the problem

**Comment by jakobii** [comment]
I ran "RAILS_ENV=production rake db:seed" as the user "Rails" and then the
demo login worked.
