### ISSUE TITLE
Let users read articles in other languages if they are not translated to the user's language

### ISSUE THREAD

**Issue by pepjo** [helpyio/helpy#38]
Hello again :smile:,

First of all, we love using helpy and we love the speed of development.

Having that said, we find that we cannot always translate the knowledge base articles to all languages before making them public. This leads to some languages having less articles. Most of our users are able to fully understand more than one language even though they prefer one or another. We feel that it would be grate to let users browse and search for articles that are not yet translated.

For example, we have a category named "Billing" in there some articles are not translated into catalan yet, but we would love that catalan users can see the links, lets say, in english. When they click the article it would load in english with a banner saying:

```
This article has not been translated to your language yet. You can read the article in the
following languages: <"spanish", "english">
```

With a drop down menu to select the available languages.

If we go further it would be possible to offer an automatically translated version apart from the versions in other languages. But this is more than what I would dare to ask for.

This is just an example of how it could work, I'm sure there are other options available, but something to handle untranslated article would be nice.

I hope you can use this as inspiration to improve heply even more :smile:

**Comment by scott** [comment]
Hi Pep!  Glad to hear it is working out for you :)  Its great to hear from actual users that are happy with the project!  

Yeah this was something that was originally planned for the multilingual feature but never got quite finished.  I will see what it will take to finish that up.  The auto translation would be great too, but AFAIK Google charges for their translation service... maybe there is an open one?

**Comment by pepjo** [comment]
Hi,

Regarding the automatic translation, I think that the proper thing to do would be to let users configure their own token in settings.yml. I think that bing translation lets you translate some phrases for free but you need a token anyways (and it's not as good as google).

All the same, I'm not sure if this is a top priority at the moment.

**Comment by scott** [comment]
Thats a pretty good idea, but I agree it is not a super high priority item.  Thanks for the suggestions :)
