### ISSUE TITLE
Community forums on the front page

### ISSUE THREAD

**Issue by noyainrain** [helpyio/helpy#388]
Hey everyone!

At the moment, besides the search field, only the knowledge base is featured on the front page. I'd really love to have an option to also include the list of community forums/topics prominently on that page.

Ideally, there would be two toggle settings (one for knowledge base, one for community forums), so one can choose to show only one category, both or even none (search field only).

It seems there are two use cases for Helpy, one being a help desk with an additional feedback forum, the other being a feedback forum with an additional help desk - more like an open source alternative to Uservoice (which btw would be some good SEO keywords, I guess, at least that's how I found Helpy). The proposed feature would make it possible to choose between the use cases.

What do you think?

Thanks for your awesome work on Helpy! :)

PS: Something along those lines has also been [requested on Helpy support](http://support.helpy.io/en/topics/247-have-community-in-front-page/posts).

**Comment by scott** [comment]
Thanks for the suggestion!  I think this is a great application for a custom theme that more prominently includes the community on the front page.  

Interesting that you found Helpy via uservoice, I never really considered Helpy to be an alternative to them.  From what I know, the most popular uses are:

1- Helpdesk- ticketing only
2- Helpdesk/ticketing with a knowledgebase
3- knowledgebase only
4- Some other combination

It seems the community forums are the lest popular feature and many folks choose to just disable that (which you can now do in the settings.)

**Comment by NoyaInRain** [comment]
Hey @scott, thanks four your reply!

Well, I would add the use case

     Feedback forum + knowledge base (~ Uservoice)

to your list (apart from *some other combination*) ;) . It may be the least popular, but maybe still relevant and it seems I'm not alone here: For example, Helpy is listed as alternative to Uservoice on [AlternativeTo](http://alternativeto.net/software/uservoice/).

I think you made a good call to say that ticketing, a knowledge base and feedback forums belong together and should be part of the same tool.

If you also think that the proposed use case is relevant, I'd still suggest to add a way to get the community forums on the front page.

I could for sure make a custom theme, but this would pretty much just be copy of one of the standard themes with a few lines changed in the front page template. I'm not sure if the small functionality warrants using a whole new theme.

Thanks again for your time and have day! :)
