### ISSUE TITLE
Prevent deleting system forums and categories

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#398]
Should not be able to delete "common replies" category, or system forums (which are currently hidden anyways.)

**Comment by rschaerer** [comment]
:boom: In addition to this, there are two potential data leaks for posts being made in the common replies category:

1.  If someone sets the common replies category to *active* (and optional also enables frontpage) the entries show up in the Knowledgebase ([Source: helpy channel](https://helpyio.slack.com/archives/general/p1476893339000027))
2. If someone sets a post's **Status: Published** and not **Draft** made in the the common repiles category, this post is being exposed by explicit URL (but it keeps not accessible through navigation from the knowledgebase) ([Source: helpy channel](https://helpyio.slack.com/archives/general/p1476893601000029))

**Comment by hin101** [comment]
I can take a look at this for you

**Comment by scott** [comment]
Awesome!

**Comment by hin101** [comment]
Pull Request #459

**Comment by rschaerer** [comment]
Hi @hin101 thanks for the PR #459 ! From your PR description I read that you didn't tackle the two issues I posted on [19 Oct](https://github.com/helpyio/helpy/issues/398#issuecomment-254865864)? (which are not related to the actual issue #398 in the first place and should have been posted as new issue anyways).

If you confirm this, I'll open a new issue with the [data leak](https://github.com/helpyio/helpy/issues/398#issuecomment-254865864) finding.

**Comment by hin101** [comment]
Hi @rschaerer I have hidden it from the front end also, but I haven't tackled 

If someone sets a post's Status: Published and not Draft made in the the common repiles category, this post is being exposed by explicit URL (but it keeps not accessible through navigation from the knowledgebase) (Source: helpy channel)

**Comment by rschaerer** [comment]
@hin101 : could the switches published & draft also made hidden for new posts and editing of posts in the common replies category? What do you think?
