### ISSUE TITLE
Private / Agents only Knowledge Base

### ISSUE THREAD

**Issue by silverskysoft** [helpyio/helpy#416]
Hello,
Is there way add topics in KB so that its accessible only to Agents or logged in users? This is so Agents can learn about internal processes etc.

**Comment by silverskysoft** [comment]
@scott any ideas?

**Comment by scott** [comment]
Currently this is not possible but its a pretty good idea and I will add it to the backlog

**Comment by Rynaro** [comment]
It's a great idea. In many companies that I have a opportunity to contribute, I see, the internal documentation is so important.
I'm working on this feature, because it's useful, and will improve the Helpy experience for agents team.

**Comment by Rynaro** [comment]
We have two options to implement this feature on Helpy.

One of them is creating a _internal_ boolean field on *Category* model, and modify, and create some scopes to virtually separate the *public* categories, and *internal* categories. And following this logic, we will need to adjust the *Doc* model too, to accept new Category flow.

And we have an option to completely separate the model, controllers, and views about *internal knowledgebase*. I think, this option isn't elegant, and creates some similar logic in two places, only for "hide" contents.

I really like the *first* option. 
What you think @scott, and @silverskysoft ?

**Comment by scott** [comment]
I thought about this as well, and thought of the first option too.  I think it makes the most sense.  Then create a simple UI inside of the admin namespace for displaying the the new internal KB.

**Comment by silverskysoft** [comment]
I agree, the first option is good. 
 @Rynaro,  Can you also please consider adding `team_list` to Category Model like how Topic model has? Not sure how much work this may add. But do let us know your thoughts.

**Comment by scott** [comment]
Hey @silverskysoft I have been on vacation so I missed this one, but I am curious of your thoughts/reason for adding `team_list` to the Category model?  Is this your suggested approach for determining which categories are "internal only" and to further offer scoping to individual teams?

**Comment by silverskysoft** [comment]
@scott, yes - as you described it. Given the teams feature exists, its almost natural to think of scoping various elements to teams. The immediate questions were:
1. I have a process A for team A. That process contains restricted info -  for example, login info to internal servers. This usually comes in organizations that have dissimilar teams.
2. General use is to limit access to such Knowledge Base articles to teams. 
3. This could also be used to limit search results to more relevant ones in future. 
I'm still trying out Helpy - so not sure if there's another way to achieve the above scoping.

**Comment by scott** [comment]
Currently there is not a way to scope views of the knowledgebase but relying on the `teams` list is a great idea.  I saw the @Rynaro started working on some stuff in his fork, but I have not looked at what he has done so far.

**Comment by Rynaro** [comment]
Actually the knowledgebase is open for all Agents to edit, and creates in any categories. We need to adjust the permissions inside the KB to deal with the Team logic.
Another thing to discuss, in Helpy we have the option to disable the KB, I think it's a good idea to split the logic into _Full KB disable_, _Public KB disable only_ and _Private KB disable only_.  What you think @scott ?
In my first effort, I create a boolean value that adjust a **Category** as a private or public. I think, controlling the KB in Category generate less logic complexity inside the Helpy instead of put this logic inside the **Doc**.

**Comment by silverskysoft** [comment]
awesome. thanks @scott & @Rynaro
