### ISSUE TITLE
Truncate long posts instead of blocking them

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#425]
Currently Helpy imposes a limit of 10,000 characters on `Posts`.  If the message is longer, it fails validation and cannot be created.  This is bad because if it is created via an email with a lot of quoted text, the `Post` will not be created, and fail silently.  Instead the better behavior would be to simply limit the character stored.

**Comment by lccezinha** [comment]
Hey @scott 

Just to clarify, accept the Post to be created with more than 10K chars, but in the view trucante to appear only 10K, is that ?

**Comment by scott** [comment]
I think actually we should only store the first 10k characters, so before it is saved, truncate it down.   Can probably actually keep the validation there, as long as the message is trimmed before saving. The view doesn't need to do anything differently that it does now.  The 10k limit is really to keep from overwhelming the server with huge emails.
