### ISSUE TITLE
Private ticket "cost/weight"

### ISSUE THREAD

**Issue by Rynaro** [helpyio/helpy#430]
In various companies I can notice a cultural (?) behavior, that designates a "monthly ticket pack" for a specific client, or other company. If the client reach the limit of your "tickets pack", this client sometimes is blocked until a new "pack" is acquired, or the ticket opening isn't blocked, but each new ticket create a "tax" on monthly value paid by client.
I think, it's a great idea to create a flexible environment, that permits to Helpy Administrator user, to choice your own "support culture". If they has these package system, they need to enable this feature, and configure the montly limit for each user. If not, Helpy keeps the actual pipeline.

**Comment by scott** [comment]
That's an interesting idea, and one I have not really heard of previously.  I think it's a good idea for an extension gem.  This is not likely functionality that would be needed by most organizations, but for those that charge for support, it make a lot of sense.
