### ISSUE TITLE
Replace suckerpunch with SideKiq

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#431]
This will implement sidekiq as the preferred queue for Helpy.  We will need to create documentation around this and mayb keep suckerpunch in development/test

**Comment by arrowcircle** [comment]
Why dont you like suckerpunch? Its super simple, dont require redis and dont need separate process

**Comment by scott** [comment]
Its not that I don't like it, I just think Sidekiq is better for real business use.  Ultimately we'll still prefer `ActiveJob` which means you can run whichever backend you want.  I just don't like that restarting the rails process loses all the jobs in memory.

**Comment by arrowcircle** [comment]
How much times did you lost jobs in production? Sidekiq is real pain for single process apps: need init and monitoring scripts.

Interesting idea - is to start sidekiq with app server, like @discourse does it.
But I dont know if its supported by passenger and puma.

**Comment by scott** [comment]
Yeah I think this one is going on hold for now.
