### ISSUE TITLE
Change Ticket User

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#433]
Overview:

This enhancement will allow administrators and agents to change the "creator" or `user_id` of a given topic.  Sometimes a need arises to move a topic from one user to another.  This can happen when splitting a topic into multiple discussions, if a user calls in with an issue or an issue is forwarded to the helpdesk.  See  http://support.helpy.io/en/topics/328-change-source-or-asker-of-a-question/posts for further ideas.

Requirements for implementation:

- There should be a button/option to change the creator of a topic.  This should appear only on the first `Post` since that is what determines `Topic` ownership.

![screen shot 2016-11-19 at 11 44 29 am](https://cloud.githubusercontent.com/assets/14369/20457714/27d48e54-ae4e-11e6-9055-328f4756229a.png)

- Upon pressing this button, a ui to search for the user should be presented in a modal window.  This should include a search form and results area so the admin can search for a user by name or email address.
- After clicking the user they would like to transfer the `Topic` to, the `user_id` will be updated for the topic and the first `Post`.
- An internal note should be added to the topic (authored by the agent who changed the Topic creator) stating: "The creator of this topic was changed from [original creator name] to [new creator name]"

**Comment by CGA1123** [comment]
@scott I don't have access to http://support.helpy.io/admin/topics/328!

**Comment by scott** [comment]
Oops also available here- http://support.helpy.io/en/topics/328-change-source-or-asker-of-a-question/posts
