### ISSUE TITLE
Merge Tickets

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#441]
This enhancement will make it possible to merge two or more topics into a single new discussion.  From the topics overview page, the agent will be able to select 2 or more topics and then click on 'Merge' to combine the messages.

Requirements and workflow:

- From a Topics overview, the agent should be able to choose two or more topics to merge (existing functionality).
- An option to "Merge" will be presented in the lower menu area (see screenshot).

![screen shot 2016-12-01 at 12 25 00 pm](https://cloud.githubusercontent.com/assets/14369/20808825/4da907e6-b7c1-11e6-9cce-ba4f265de049.png)

- After clicking merge, a dialogue should be presented, confirming the desire to merge the Topics.
- Upon confirming, a new Topic should be created, by creating a copy of the chronologically **first** Topic selected.
- The title of the new Topic should be retained, but prepended with "MERGED: "
- The Posts from each of the selected topics will be copied into the new Topic.
- The selected Topics will be moved to trash.
- An internal note should be written to the new merged Topic stating "%{topic.id}-%{topic.name}, etc. were merged to create this discussion"

**Comment by hin101** [comment]
Ill pick this one up :)
