### ISSUE TITLE
Add the ability to embed a Youtube video in a doc

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#444]
This will allow you to embed a Youtube video into a doc.  Basically what needs to happen is to add a form field that accepts the URL of the youtube video, and then insert it into the trix editor window.  This should exist on `admin::doc#edit` and `#create`

See: https://helpyio.slack.com/archives/general/p1477939555000065
https://github.com/basecamp/trix/issues/120

**Comment by danmitchell-** [comment]
+1 for this. I'd like the code block to except HTML embed's i.e. youtube/vimeo etc

**Comment by fbmore** [comment]
Hello... any news on this? I love the editor and I'd like to allow my users to be able to embed videos too. Thank you!

**Comment by scott** [comment]
I just switched editors to summernote (https://github.com/helpyio/helpy/commit/5f87cda3ff4f41a5413d61f6a3eecd4b5284bf46) which supports video embeds and some other neat stuff.  It is a great editor too.  If you update to the newest master, you will see that it is updated!
