### ISSUE TITLE
Update grape-entity

### ISSUE THREAD

**Issue by connorshea** [helpyio/helpy#455]
https://groups.google.com/forum/m/#!topic/ruby-grape/H7O3fX8TA24

There's a security vulnerability in versions before 0.6.0.

**Comment by CGA1123** [comment]
Are you working on a PR for this?

The [`CHANGELOG`](https://github.com/ruby-grape/grape-entity/blob/master/CHANGELOG.md#060-2016-11-20) for `0.6.0` doesn't mention any breaking changes.
