### ISSUE TITLE
delete a user

### ISSUE THREAD

**Issue by hadifarnoud** [helpyio/helpy#457]
sometimes there are newsletters and other spam emails that show up and those are not real users. would be great to be able to delete them

**Comment by wilsonpeng8** [comment]
ive also noticed theres no way to delete a user from the user list

**Comment by micah** [comment]
I was just searching how to delete a user, and I couldn't find one, so I came here to file an issue, and looks like there is one!

**Comment by tomatoturnip** [comment]
Is anyone working on a PR for this? If not, I can start on it.

**Comment by scott** [comment]
I am not aware of anyone working on this.  A PR would be great!

**Comment by tomatoturnip** [comment]
Cool I'll get started on it. Thanks @scott! :)

**Comment by scott** [comment]
Awesome.  I think it would be ideal to put this into a background job once you have it working in principal.
