### ISSUE TITLE
email still not working

### ISSUE THREAD

**Issue by wilsonpeng8** [helpyio/helpy#460]
ive tried mailgun and even followed the full instructions for sendgrid but i still cant eeceive notification and invitations emails from both, anybody help?

**Comment by scott** [comment]
What version including SHA are you on? I think there may be an issue with something that was merged in a few days ago.  Also, are you using the standard suckerpunch queue or something different?

**Comment by scott** [comment]
Did you get this working?  I am closing this since you have not replied, but reply if you still have an issue.
