### ISSUE TITLE
SMS integration

### ISSUE THREAD

**Issue by rhazegh** [helpyio/helpy#465]
Is there already SMS integration or plans to include SMS integration via services such as twilio?

**Comment by scott** [comment]
There is not yet, but its a good idea that I have added to the backlog.  I think this would be a good add-on/extension.

**Comment by scott** [comment]
Can you expand a little bit on how the integration might work and what problems it would solve?

**Comment by rhazegh** [comment]
SMS integration allows your customers to communicate with the help desk using any kind of cell phone by sending a text message or a picture to tell you what kind of problems they are experiencing. 

In this case, the customers will naturally expect a quicker response. You could have you customer support to address these issues with a higher priority or almost in real time.

This idea could be expanded to other messaging platforms such as Facebook messenger, etc ...

**Comment by simzen85** [comment]
+1

For example Zendesk can receives "message" (then create ticket) via Facebook Messenger, phone call from Call Center software

**Comment by pinkasey** [comment]
I'm interested in integration with Facebook.

The popular use-case would be that a company has a facebook-page, and the CS Team expects any message to that page, and any post to that page, would translate to a ticket in the Helpdesk.

In my use-case, the company has many groups, and each CSR is associated with a Facebook group, and I would like any post to that group **that is not posted by a CSR** would be translated to a ticket.
