### ISSUE TITLE
Help Needed!  Maintainer for Docker.

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#469]
We currently need a community member to help out with maintaining the docker container for Helpy.   This means updating the container scripts to keep in line with the release cycle of Helpy, making sure everything works correctly, and helping users as needed.  Please reply here if you can help!

**Comment by Lubo** [comment]
Why don't you just import Dockerfile to this repository and let Docker Hub build it when a new tag is pushed ? This way, nobody would have to keep up with anything. I can help out with initial setup and writing Dockerfile (I've seen some Dockerfiles on @helpyio, but I don't like them).

**Comment by lacion** [comment]
agree with @Lubo  there is no need to have 2 separate repos for this. it would be much easier to have it all here.
