### ISSUE TITLE
Inactiveting users

### ISSUE THREAD

**Issue by neliojrr** [helpyio/helpy#476]
Is the 'Active' checkbox working? 
I tried to set off but it doesn't seems to work. The checkbox is unchecked and in the database the users column 'active' is set as false but the user is still able to log in.

**Comment by scott** [comment]
Hmmm sounds like a bug, thanks for reporting.  Will see if we can fix it :)

**Comment by CGA1123** [comment]
Had a little look at this, seems that there is indeed a field in the `users` table. But I can't see any overriding of `Devise::SessionsController` adding in an extra check for that field.

**Comment by scott** [comment]
If you want, go ahead and submit a PR :)

**Comment by sesharim** [comment]
@CGA1123 hi, have you started it or i could?

**Comment by CGA1123** [comment]
@sesharim feel free to start on it. You just need to create a cutom devise controller, with an extra check for `User#active` before allowing a sign in.

There's some helpful pointers [here](https://github.com/plataformatec/devise#configuring-controllers) for how you might start off.

**Comment by scott** [comment]
Hey @sesharim any updates on this?
