### ISSUE TITLE
New "Companies using Helpy" List

### ISSUE THREAD

**Issue by olliebennett** [helpyio/helpy#48]
A good way to engage with the community; it would be nice to have a list somewhere of companies using this tool. It would provide a sense of security and community adoption which could help uptake.

**Comment by scott** [comment]
I think this is a great idea.  I originally considered adding a place where people could post screenshots of their customization/design as well, but I have been waiting to get more adoption.

**Comment by olliebennett** [comment]
Great. Let me know whether you'd rather keep that in GitHub (i.e. the README) or as knowledgebase content on support.helpy.io perhaps.

As to your "themes" suggestion, users could always use an existing Bootstrap theme (eg. from [Bootswatch](https://bootswatch.com/), but I agree it would be good to structure our own sass files to allow easier customisation or "theme swaps" down the line. Will keep that in mind.

**Comment by scott** [comment]
Yeah I want to get some of the theme stylings into `settings.yml` like the basic colors, logo, fonts, etc.  We could also a variable to point to an entire bootstrap theme.
