### ISSUE TITLE
"Discussions" should be renamed "Tickets"

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#495]
After talking with a number of users, it seems that the word "discussions" creates quite a bit of confusion- many customers do not like the concept of "discussion" because it means an open community thread as opposed to a private ticket.  This change will alter the system to use the word 'tickets' in most places, and a new theme will suffice to handle the community forum.

**Comment by Dayjo** [comment]
👍  think this is very wise

**Comment by samtuke** [comment]
+1
