### ISSUE TITLE
Add support for custom HTML email templates

### ISSUE THREAD

**Issue by samtuke** [helpyio/helpy#500]
Please add support for custom HTML email templates, e.g. including company logo, social media links etc. We already have standard HTML emails to ensure consistent branding across customer-facing services but currently it does not appear possible to use them for Helpy-generated emails.

**Comment by scott** [comment]
Thanks for making these suggestions!  We'll add them into the backlog and prioritize them for dev, unless you want to submit a PR.

**Comment by hin101** [comment]
Hi @samtuke @scott I don't mind taking a look at this. Could you provide more details?

**Comment by samtuke** [comment]
@hin101 For me, simply allowing the saving of HTML templates, and automatic insertion of messages into these templates when they are sent by Helpy, would be sufficient. If the template can be previewed / rendered in-browser, that would be even better. Multiple categories of template may be required for different kinds of emails, e.g. template for emails to admins vs emails to customers. A category for priority / VIP customers would be useful. Automatic inlining of CSS saved within HTML inside <style> tags would also be useful (some mail clients still require this) - various Open Source libraries exist for this purpose.

Hope that those initial ideas help!

**Comment by Vad1mo** [comment]
There is a very nice and easy to user templating language for e-mail. It called [mjml][1]  there is even a [ruby gem][2] that makes the work with rails even easier.

It would be easy to add upload form for various templates in the the admin section so the user can could upload his mjml files. Alternatively a single HTML file that contains everything.   

[1]: https://mjml.io/
[2]: https://github.com/kolybasov/mjml-ruby
