### ISSUE TITLE
Question about requests to 3rd parties

### ISSUE THREAD

**Issue by disturbio** [helpyio/helpy#503]
Would you accept a patch to make requests to 3rd parties (like google analytics, fonts or jsdelivr) optional? we currently on the process to deploy helpy and our users are very privacy minded, meaning we need to strip all of those. It will be cool if we don't have to maintain those changes only in our own fork.

**Comment by scott** [comment]
Yes this would be a valuable addition.  Send over a PR and we can work a little to integrate it into the overall platform as needed.
