### ISSUE TITLE
Use absolute paths in widget code snippet

### ISSUE THREAD

**Issue by samtuke** [helpyio/helpy#518]
Currently the auto-generated widget code snippet is failing to load the widget on my local development server. 

Code used:
```js
<script>
  var Helpy = Helpy || {};
  Helpy.domain = 'phplist.helpy.io';
</script>
<script src='//phplist.helpy.io/assets/widget.v1.js'></script>
```

This results in 404 errors. If the paths are made absolute, including http://, then the problem is resolved.

**Comment by freecrm** [comment]
It is also broken on SSL but that's another bug.
