### ISSUE TITLE
[nitpick] "Log in" or "Sign in"?

### ISSUE THREAD

**Issue by monaka** [helpyio/helpy#542]
On the UI, there have "Log in" and "Sign in". Can we unify them?

**Comment by Rynaro** [comment]
I see in Helpy code, we have few lines that writes "Log in", and all the others refers to "Sign in". I suggest to define a pattern using "Sign in".

**Comment by CGA1123** [comment]
Are these lines hardcoded?

**Comment by Rynaro** [comment]
Yes, these lines are hardcoded on elements, and `en.yml` have one rule that writes "Log in".
All the others rules refers to "Sign in" sentence.

**Comment by scott** [comment]
Yeah I think "Sign in" is preferable.  We should update any non `i18n` instances of either to use the translations and then update en.yml to user "sign in" instead of "log in".
