### ISSUE TITLE
500 error with attachments that have multi-byte character filenames.

### ISSUE THREAD

**Issue by monaka** [helpyio/helpy#543]
My helpy is customized and I apologize when this is caused by customize.

I got  an 500 error after submitting reply with attachments that have multi-byte character filenames. 
Log is like this.

```
ActionView::Template::Error (URI must be ascii only "https://{censored}.blob.core.windows.net/helpy/uploads/post/attachments/49/\u{5143}\u{306e}\u{30e1}\u{30fc}\u{30eb}.txt"):
```

I guess filenames should be encoded before passing CarrierWave.

**Comment by monaka** [comment]
Update.
The whole log is like this. And CarrierWave (I customize it to use with Azure Blob) stores attachments correctly.
Filenames should be encoded before storing to DB or after getting from DB.

```
Completed 500 Internal Server Error in 1111ms (ActiveRecord: 768.2ms)

ActionView::Template::Error (URI must be ascii only "https://{censored}.blob.core.windows.net/helpy/uploads/post/attachments/49/\u{5143}\u{306e}\u{30e1}\u{30fc}\u{30eb}.txt"):
    15:         <% if %w(png jpg jpeg gif).include?(att.file.extension) %>
    16:           <%= link_to image_tag(att, style: "width: 125px; height: 125px"), att.url, class: 'screenshot-link', target: 'blank' %>
    17:         <% else %>
    18:           <%= link_to att.url, title: att.url, target: 'blank' do %>
    19:             <%= content_tag(:i, '', class: attachment_icon(att.url)) %>
    20:           <% end %>
    21:         <% end %>
  app/views/posts/_attachment.html.erb:18:in `block (4 levels) in _app_views_posts__attachment_html_erb__2836734086973453099_47349722287320'
  app/views/posts/_attachment.html.erb:14:in `block (3 levels) in _app_views_posts__attachment_html_erb__2836734086973453099_47349722287320'
  app/views/posts/_attachment.html.erb:13:in `each'
  app/views/posts/_attachment.html.erb:13:in `block (2 levels) in _app_views_posts__attachment_html_erb__2836734086973453099_47349722287320'
  app/views/posts/_attachment.html.erb:12:in `block in _app_views_posts__attachment_html_erb__2836734086973453099_47349722287320'
  app/views/posts/_attachment.html.erb:11:in `_app_views_posts__attachment_html_erb__2836734086973453099_47349722287320'
  app/views/admin/topics/_post.html.erb:28:in `_app_views_admin_topics__post_html_erb___3968004254807639614_47349721144820'
  app/views/admin/topics/_ticket.html.erb:20:in `_app_views_admin_topics__ticket_html_erb___2427613158569892413_47349712742540'
  app/views/admin/topics/show.js.erb:1:in `_app_views_admin_topics_show_js_erb___1959363208674178946_47349712510780'
  app/controllers/application_controller.rb:202:in `set_time_zone'
```

**Comment by monaka** [comment]
In addition and IMO, should attachments be stored behind the hashed directory?
In the current implementation, crackers may prospect URL to attachments easily.

**Comment by Rynaro** [comment]
I see your main language is Japanese, and your language uses non-ASCII patterns. I need to test more the upload methods, but the problem can show to another languages characters patterns.
But looking this log trace, is clear to me. The application don't sanitize the non-ASCII characters correctly.

I need to check this behavior more closer to create a non-intrusive and best-fit solution.

**Comment by Rynaro** [comment]
@monaka I've made some test using Kanji characters and all Helpy controllers, and views could render the attachments (images, raw text files). Can you give more details how reproduce this error?

**Comment by monaka** [comment]
This will be reproduced just sending an attachment file named in Kanji.
And probably also Emoji characters.
I can try your patch on my site if you open it.

**Comment by Rynaro** [comment]
First I made a test with a pure instance of Helpy, based on helpy/master. And all Kanji file named, are uploaded, and rendered on your respective views. 
Or your instance has a particular modification that causes this problem, or I don't try all cases what your faced. I only tried Kanji characters, and the pure instance of Helpy works well.
In (Brazilian) portuguese we have some few multibyte characters too, and I don't have faced this problem. :smile:

**Comment by monaka** [comment]
Exactly I have a tiny modification for using Azure Blob with CarrierWave.
But it's hard to explain how my patch causes this issue, IMO.
Okay, I'll try to reproduce and to make new patch. Thank you for your checks.

**Comment by monaka** [comment]
@rynaro Could you tell me what version of Ruby are you using?
Reffering to README.md, Helpy requires Ruby 2.2+. And URL/URI handlings are changed in Ruby 2.3.
I'm not sure the changes causes this issue. Just possibility.

**Comment by monaka** [comment]
I got an another 500 exception in displaying avatar in addition to attachments.
(But there is no exception on the logo even thought they are same PNG file. I'm not figure out why...)

```
app  | ActionView::Template::Error (URI must be ascii only "https://{censored}.blob.core.windows.net/helpy/support/uploads/user/profile_image/1/\u{7e26}\u{7d44}\u{307f}_\u{767d}\u{629c}\u{304d}.jpg"):
app  |     34:     <div id="written-by" class="doc-meta">
app  |     35:       <div class="more-important meta-header"><%= I18n.t("written_by", default: "Written By") %>:</div>
app  |     36:       <div class="less-important">
app  |     37:         <%= avatar_image(@doc.user, size=40) %>
app  |     38:         <%= @doc.user.name.titleize %>
app  |     39:       </div>
app  |     40:     </div>
app  |   app/helpers/users_helper.rb:84:in `avatar_image'
app  |   app/views/docs/show.html.erb:37:in `_app_views_docs_show_html_erb___2093955696365140870_47010139175040'
```

And, I found [a commit to CarrierWave related on URL encoding](https://github.com/carrierwaveuploader/carrierwave/commit/8ee0f879e656ee788a2df67b31e724e952399578).
In addition, I found the article describes the background of this patch [writen in Japanese](http://qiita.com/koic/items/c0dd77ff853de72c1597).
 
So, it seems @Rynaro is right.
This issue is caused not by Helpy.
But CarrierWave (and/or CarrierWave-Azure) and/or Ruby versions.

I close this issue. Thanks for your support.
