### ISSUE TITLE
Can't put Helpy into sub URL path.

### ISSUE THREAD

**Issue by monaka** [helpyio/helpy#563]
My customer want to use Helpy in their Web application.
'/' has already used by the application. So the instance of Helpy must be located `/support/`  or somewhere.
But the master branch of Helpy doesn't care about this case.
( I have a half-baked patch and I can send it as the pull request. )

**Comment by scott** [comment]
I played around with this idea once a long time ago- I was able to get it to work in a `/support` directory by adjusting some of the routes.

**Comment by monaka** [comment]
@scott There have some client side scripts that have absolute links in the current master branch. So I think we must apply patches to `assets/`.

**Comment by monaka** [comment]
Close this as too old.
