### ISSUE TITLE
Hide trashed and spammy comments from knowledge base

### ISSUE THREAD

**Issue by azul** [helpyio/helpy#573]
After putting comments on helpdesk articles in the trash or marking them as spam they still show up.

**Comment by hin101** [comment]
@azul could you let me know how to reproduce this bug, I have tried it on my dev and it works fine, thanks

**Comment by scott** [comment]
This is actually how it is designed.  You can make the objectionable `Post` object inactive or edit it, but it is not possible to remove the `Topic` thread.
