### ISSUE TITLE
no implicit conversion of Symbol into Integer

### ISSUE THREAD

**Issue by letlive** [helpyio/helpy#596]
Hi,

I tried to install Helpy on Debian Jessie, however, 'bundle install' reported an error as below:

――― ERROR REPORT TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――
- What did you do?
- What did you expect to happen?
- What happened instead?

Error details

    TypeError: no implicit conversion of Symbol into Integer
    /home/rails/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/ruby_dsl.rb:4:in `[]'
    /home/rails/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/ruby_dsl.rb:4:in `ruby'
    /srv/helpy/Gemfile:193:in `eval_gemfile'
    /home/rails/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/dsl.rb:32:in `instance_eval'
    /home/rails/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/dsl.rb:32:in `eval_gemfile'
    /home/rails/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/dsl.rb:10:in `evaluate'
    /home/rails/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/definition.rb:25:in `build'
    /home/rails/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler.rb:155:in `definition'
    /home/rails/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/cli/install.rb:78:in `run'
    /home/rails/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/cli.rb:157:in `install'
    /home/rails/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/vendor/thor/command.rb:27:in `run'
    /home/rails/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
    /home/rails/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/vendor/thor.rb:363:in `dispatch'
    /home/rails/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/vendor/thor/base.rb:440:in `start'
    /home/rails/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/cli.rb:10:in `start'
    /home/rails/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/bin/bundle:20:in `block in <top (required)>'
    /home/rails/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/lib/bundler/friendly_errors.rb:6:in `with_friendly_errors'
    /home/rails/.rvm/gems/ruby-2.2.1@global/gems/bundler-1.8.4/bin/bundle:18:in `<top (required)>'
    /home/rails/.rvm/gems/ruby-2.2.1@global/bin/bundle:23:in `load'
    /home/rails/.rvm/gems/ruby-2.2.1@global/bin/bundle:23:in `<main>'
    /home/rails/.rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `eval'
    /home/rails/.rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `<main>'

Environment

    Bundler   1.8.4
    Rubygems  2.4.6
    Ruby      2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
    GEM_HOME  /home/rails/.rvm/gems/ruby-2.2.1
    GEM_PATH  /home/rails/.rvm/gems/ruby-2.2.1:/home/rails/.rvm/gems/ruby-2.2.1@global
    RVM       1.29.1 (latest)
    Git       2.1.4
    rubygems-bundler (1.4.4)
――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by scott** [comment]
Did you get it to work?  I am curious if you had to do anything special to get it installed on Debian?

**Comment by letlive** [comment]
Hi @scott, No, I didn't do anything special. I tried according to the steps in Ubuntu.
