### ISSUE TITLE
Forgot login credentials

### ISSUE THREAD

**Issue by wondersoftheworld** [helpyio/helpy#606]
hey scott & co, thanks for making this available as open source.
i used your one click install to heroku some time ago and the installation is still active. however, i totally forgot the login credentials i setup initially so i am unable to login or use the installation at all. how can i retrieve or reset my setup login credentials? i tried the forgot password link but no password was received probably because i did not go that far in the settings to setup email when i initially installed my instance.
any help will be much appreciated.
thanks.

**Comment by scott** [comment]
Hey @wondersoftheworld I am not sure what the best way to approach this is.  Can you access the database directly?  If you can, you could sign up a new user through the web, then change them into an admin in the database table- then log in with the new admin, go ahead and set up the email so you receive the reset messages.  One idea...  Another is to up the log level and then try and grab the reset url out of the logs when it tries to email you...
