### ISSUE TITLE
500 Server Error when opening tickets

### ISSUE THREAD

**Issue by snxraven** [helpyio/helpy#618]
I, [2017-04-25T22:48:57.941337 #1528]  INFO -- : Completed 500 Internal Server Error in 101ms (ActiveRecord: 0.5ms)
F, [2017-04-25T22:48:57.945774 #1528] FATAL -- : 
ActionView::MissingTemplate (Missing template topics/create, application/create with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :jbuilder]}. Searched in:
  * "/home/rails/JBBar/JBBar-Helpy/app/themes/light/views"
  * "/home/rails/JBBar/JBBar-Helpy/app/views"
  * "/home/rails/.rvm/gems/ruby-2.2.1/gems/devise_invitable-1.6.0/app/views"
  * "/home/rails/.rvm/gems/ruby-2.2.1/gems/twitter-bootstrap-rails-3.2.2/app/views"
  * "/home/rails/.rvm/gems/ruby-2.2.1/gems/kaminari-0.16.3/app/views"
  * "/home/rails/.rvm/gems/ruby-2.2.1/gems/grape-swagger-rails-0.3.0/app/views"
  * "/home/rails/.rvm/gems/ruby-2.2.1/gems/devise-bootstrap-views-0.0.8/app/views"
  * "/home/rails/.rvm/gems/ruby-2.2.1/gems/devise-i18n-1.0.1/app/views"
  * "/home/rails/.rvm/gems/ruby-2.2.1/gems/devise-3.5.6/app/views"

**Comment by scott** [comment]
I am not sure what to do with this.  If you are still having problems please provide details on how to recreate the issue.

**Comment by jbova** [comment]
Hi snxraven,

See if you're example meets the following conditions:
1) You have recapcha enabled
2) You are logged in
3) The recaptcha challenge is not displayed on the new topic page

If so, please try disabling recaptcha and trying to create a new ticket.

I believe the issue has to do with the following in the topics controller:
`if recaptcha_enabled?
      render :new && return unless verify_recaptcha(model: @topic)
    end
`
The site doesn't know to render the topics/index.html.rb view, and instead is looking for topics/create.html.rb.

Thanks,
Jim
