### ISSUE TITLE
Bug in the knowledge base

### ISSUE THREAD

**Issue by Estumer** [helpyio/helpy#636]
When you click on the categories on the left it does not detect the category. However, if you are within a category the menu on the left works correctly. Sorry for bad english!

**Comment by scott** [comment]
This is not actually a bug, but rather autoscrolls to the category and docs for that category on the right.  (see [http://support.helpy.io/en/knowledgebase](http://support.helpy.io/en/knowledgebase))  With a small number of articles this does not happen, which is probably what you saw.

**Comment by indagreen** [comment]
or maybe i should be writing in this thread

**Comment by scott** [comment]
I think you have the wrong person, i have no idea who you are or what you are talking about

**Comment by indagreen** [comment]
then why are you in my laptop? phones? fire stick? i found you through my email. don't play dumb, please, i believe you are much more intelligent than that. give yourself a little more credit and please give me something for the hours i have put in to tracking some people down. if you want to play it your way, fine...i'll play along for your sake, but i need help. i think you can at least do that. not sure how long you've been here all i know is i've read your stuff. will you help?

**Comment by indagreen** [comment]
are you an honorable person/s? are you causing all this havoc in my life? show me how to undo. tell me how to unlock my phone. fire stick was useless, had to return. geek squad has it now, and no, i didn't get my money back. and i only got to use the phone i bought for a week. i do not work any more, i am disabled and now worse. my life is quite uneventful so i offer my spare time to one of you to teach me. can you do that? or do i just keep learning a bit at a time deleting and force stopping? are you capable of teaching me? let's start with unlocking my phone. what do ya say?
