### ISSUE TITLE
/home/helpyuser is not a directory

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#645]
When testing the docker-compose, I saw this error:

```helpy_1     | `/home/helpyuser` is not a directory.
helpy_1     | Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.```

It seems to work okay, but this doesn't look right.  Anyone have any ideas?

**Comment by nh-99** [comment]
Seems to be related to how the user helpyuser is created. The specific command is `useradd --no-create-home $HELPY_USER`. It doesn't setup a home directory for the user, so when the bundler tries to stores gems there it can't find it. Everything seems to work as intended, so probably not a bug that needs fixing.
