### ISSUE TITLE
Configuration via ENV vars

### ISSUE THREAD

**Issue by olliebennett** [helpyio/helpy#65]
I propose we support configuration of Helpy via environment variables. The `settings.yml` is great, but it could be a nice idea to have, for example:

```yaml
parent_site: ENV['SITE_NAME'] || `/parent-redirect.html`
```

This would allow us to configure most (all?) configuration via environment variables.

It would also make the "Deploy to Heroku" button really trivial to use; we could ask for the required info during deployment.

See also: [Heroku "config vars" docs](https://devcenter.heroku.com/articles/config-vars).

**Comment by scott** [comment]
I think thats a really good idea.  I still question the viability of Heroku for long term use however- simply due to its cost.  But that is a different topic for a different thread.  In terms of making it really easy to get up and running, there is no equal.

**Comment by scott** [comment]
@olliebennett  Is there a way to script the heroku deployment to request the needed ENV vars that you know of?

**Comment by olliebennett** [comment]
Yes - it's all documented really clearly in the [app.json schema](https://devcenter.heroku.com/articles/app-json-schema#env).

**Comment by scott** [comment]
This is now handled through the admin settings inside of Helpy
