### ISSUE TITLE
Can't activate notifications on my account

### ISSUE THREAD

**Issue by bogdanrn** [helpyio/helpy#651]
I just realised i don't recieve email notifications for tickets. So i setted up smtp settings and then tried to enable in preferences to recieve them. 
![image](https://user-images.githubusercontent.com/5882067/27387708-21fd304c-56a2-11e7-93f2-f7a3591bbe0a.png)

After i hit save, the checkboxes toggle back to off. 
I'm using google chrome on mac os, helpy is version: 1.2.1:e481018

**Comment by scott** [comment]
I see the problem.  That appears to be a bug, as notifications have been moved to the profile page and should not be showing up there.  If you go to your profile page and look at the bottom you will be able to turn them on.

**Comment by scott** [comment]
Fixed in #652
