### ISSUE TITLE
Internal mode.

### ISSUE THREAD

**Issue by caiotarifa** [helpyio/helpy#655]
I want to use Helpy for internal support, but it would be necessary to adapt with the following resources:

- Allow user management (including delete - #545) only by the admin, in other words "disallow global registration".
- Allow the ticket creation only by authenticated users.

What do you think?

**Comment by scott** [comment]
Certainly possible to do these things without too much modification!  Send a PR if you build any of this.

**Comment by scott** [comment]
This is possible with our on-premise cloud version.  Closing from here since this is over a year old.
