### ISSUE TITLE
When I save my profile (as an admin) it logs me out.

### ISSUE THREAD

**Issue by david-adams** [helpyio/helpy#677]
http://chargeback.helpy.io/admin/settings/profile?locale=en&mode=settings

If I hit "save" from this page, whether I change anything in my profile or not, I end up on this page: http://chargeback.helpy.io/en/users/sign_in and need to log in again.

**Comment by scott** [comment]
Hey @david-adams I have not been able to reproduce this myself, can you give it another try and see if there are any specific steps to reproduce it.

**Comment by scott** [comment]
Note- this was caused by the LastPass plugin autofilling the password field- which does by design cause a logout
