### ISSUE TITLE
API? 

### ISSUE THREAD

**Issue by mario** [helpyio/helpy#68]
Hey mate, was just wondering if you have any plans for an API?

**Comment by scott** [comment]
Yes!  At one point a contributor contacted me about actually building it, but he got busy with life and had to put the work on hold...

**Comment by olliebennett** [comment]
I'd be interested in hearing what you planned to build on top of the API. What kind of integration are you planning?

**Comment by scott** [comment]
There is another thread over on http://support.helpy.io/en/topics/51-is-there-an-api-option/posts about the same thing.

**Comment by mario** [comment]
I was actually planning on building mobile apps for Helpy, and a support SDK for mobile apps on top of it ... just wanted to check if you have API before I contact you to discuss details (and my ideas) regarding that. If you've got an email that I can hit ... ^_^

**Comment by olliebennett** [comment]
It would be great to have an SDK for Android/iOS which allowed app users to have conversations with the support team through Helpy.

I also think there's a lot of value in a (perhaps hybrid) app for the Admin interface, which would provide the support team with updates to their assigned topics etc, allowing for more timely responses.

**Comment by scott** [comment]
@olliebennett I agree on both- in fact the admin app/SDK is something that I had in the back of my mind from the beginning.  @mario We have a slack room set up, shoot me an email at hello at scottmiller.io and we can discuss this more offline.

**Comment by jmarnold** [comment]
Loving all of the work y'all have done so far! Just curious, how in-depth is the API work you have planned? The one killer feature I'm looking around for is Slack integration since my organization thrives on it. Is that anywhere in your plans yet?

**Comment by scott** [comment]
@jmarnold Slack integration is definitely something I have been thinking of.  Slack integration can mean a few things- are you thinking more of getting alerts in Slack when there is a new discussion, being able to reply to discussions through slack, or both?

**Comment by jmarnold** [comment]
@scott Oh man, I wasn't thinking of going too crazy ;). I was just thinking of some basic notifications. My organization uses Slack as kind of the hub of ALL information so being able to push stuff there would be HUGE.

**Comment by mbajur** [comment]
Creating a slack integration you described @jmarnold (push notifications) should be pretty simple using rails observers or monkey patching models. Anyway, that's still a monkey patching which is a bad thing. On the other hand, i'm not sure (that's my personal opinion, i'm not part of helpy team) if things like slack integration should be a part of the core. Are there maybe any plans for creating a plugins/hooks system for helpy ? That would make a huge sense. I could even came up with a slack plugin then cause my organisation needs one as well.

**Comment by scott** [comment]
I agree this is a better thing for a plugin/gem.  I have been working on a plugin system that will leverage engines and deface for adding/modifying the core UI.

**Comment by mbajur** [comment]
You sure about deface? I can hear people complains a lot about it, there is a fork of spree that came up recently which dropped deface support, not sure why though but i kind of trust those guys http://solidus.io/

**Comment by scott** [comment]
@jmarnold @mbajur Slack integration: [Helpy_Slack](http://github.com/helpyio/helpy_slack)

**Comment by jmarnold** [comment]
@scott Nice! Thanks!
