### ISSUE TITLE
Replying with the same email it was sent to

### ISSUE THREAD

**Issue by jsavalle** [helpyio/helpy#684]
Is there an easy way to customise the reply email so that answers use the same "from" email that it was addressed to? As well as the subject line?

I went through the config files and admin interface I don't seem to see anything like that. I don't mind digging in the code but if some direction about which controler or which aspect to look at that would be great.

**Comment by scott** [comment]
Yeah you can do that by editing the mailer templates and mailers themselves.  To edit the `from` address or `subject` line, you will want to edit the mailer here: `app\mailers\post_mailer.rb` for example.

To set it to the address it was sent to, change `from` to use `@post.topic.user.email`

To edit the body of the emails, those are over in `app\views\post_mailer`,  `app\views\topic_mailer`, etc.

**Comment by jsavalle** [comment]
ok, it works great... but I apparently didn't explained myself properly.

app is installed with a default email like support@domain.com

but users send an email at serviceA@domain.com and I have set up the inbound parsing to catch these too.

Now it would make more sense that the user get an answer from serviceA@domain.com than from support@domain.com

Couldn't find a way to look at it
I'll have a look at the models

**Comment by scott** [comment]
We chatted about this so I think it is resolved, but for anyone else that bumps into this, you need to set up alternate from email addresses in the groups dialogue and use that.
