### ISSUE TITLE
Improved Docker image

### ISSUE THREAD

**Issue by Vad1mo** [helpyio/helpy#695]
I would like to open a PR and improve the Dockerfile. 
Currently there are quire a few issues and problems. I would like to improve it. 

1. NO Git clone during build
2. Faster image build, seconds instead of hours. 
2. Reduced Size to about 200-300MB
3. hub.docker compatible build.
    There will be **latest** on each commit, Version TAG on each git TAG on master. And a stable build on each versioned tag. 

Before I dig into it I would like to know if you are OK with those major changes to the Dockerfile.

**Comment by ypcs** [comment]
Related to this, #951 .
