### ISSUE TITLE
Add an icon if the ticket has any attachments

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#701]
It would be awesome to have a little icon in `admin/topics/_topic.html.erb` that appears next to the ticket name if there is a file attached to the ticket.

**Comment by esunder** [comment]
Would something like this be acceptable? How many different locations need the icon?

![image](https://user-images.githubusercontent.com/357754/31059921-dfc1f37a-a6ce-11e7-84ce-54e8c4c02506.png)

**Comment by scott** [comment]
Yeah thats what i was thinking of.  Really the only place that needs it is the `_topic.html.erb` partial

**Comment by esunder** [comment]
Ok, I will look at it. Thanks!
