### ISSUE TITLE
Add priority to the Topic model

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#702]
It would be useful to have a priority for tickets.  There is currently a priority for users/customers, but it would be good to add a separate priority for individual tickets as well.  The requirements for this:

- Priority values should be 'low','normal','high','very high' . normal should be the default.
- Add a new indexed string field to the `Topic` model for priority
- Provide a select field to set the priority from the `admin/topics/_new_topic` form
- Add the priority to the Topic model api entity and associated add and update endpoints in the Topic api.
- Add the ability to set the priority through the inbound webhook (`webhooks/inbound_controller.rb`

**Comment by yoonwaiyan** [comment]
Hi, can I help out with this issue? I looked at the source code, would like to confirm the topic is represented as `message` in `inbound_controller.rb`?

**Comment by CGA1123** [comment]
@yoonwaiyan Looking at the code for [`Webhook::InboundController#form`](https://github.com/helpyio/helpy/blob/5020e013efca901dad4c1cd89ee3dd7791e74ff9/app/controllers/webhook/inbound_controller.rb#L36) that seems to be the case.

**Comment by scott** [comment]
Hey @Yoonwaiyan thanks for your interest.  Another person has already contacted me about this one, but I think you might be able to divide it up, since it touches a lot of places.  Let me see if he can join this thread and we can work it out so you each get a PR :)

**Comment by yoonwaiyan** [comment]
@scott thanks, I agree and it's a good idea to divide this up :) FYI I just created a migration to add this column in my fork, I can create a PR first or I can take the first 2-3 subtasks as mentioned.

**Comment by scott** [comment]
Yeah go ahead and do a PR for the migration and then you can work on the subtasks.

**Comment by jeffdill2** [comment]
Hi @yoonwaiyan, dividing it up sounds good to me. 😄

@scott , did you have any thoughts about the best way to break this up?

**Comment by scott** [comment]
I think one person could take the UI changes, and webhook, the other the api?  overall its not a huge amount of work

**Comment by yoonwaiyan** [comment]
I would like to take the Grape API/entity, what do you think @jeffdill2 ?

**Comment by jeffdill2** [comment]
@yoonwaiyan go for it ☺️

**Comment by jeffdill2** [comment]
@yoonwaiyan you can actually take the whole thing. I'm getting pulled into another project. Sorry!
