### ISSUE TITLE
Feed back bounced email notifications from mailgun, etc. back into helpy

### ISSUE THREAD

**Issue by rschaerer** [helpyio/helpy#71]
Since some customers enter a wrong email address, some emails bounce. This is nowhere reflected in helpy.

Up to now, I have to watch the logs of the provider like mailgun to know which email communication fails.

It would be nice if bounces could be somehow reflected in helpy. Maybe by setting the ticket status back to in progress or at least on a dedicated view where i can watch my bounced e-mails.

**Comment by scott** [comment]
Thats a good idea, will have to take a look and see how difficult it would be to incorporate.
