### ISSUE TITLE
Feature request: Multiple configurable new_user email messages (per incoming channel)

### ISSUE THREAD

**Issue by rschaerer** [helpyio/helpy#711]
## Context of the request

We have several email Addresses routed to helpy (like info@, support@, etc.) and everyone is getting the same ``new_user`` message. This is for some customer confusing: They contacted just the general inquiry info@ but receive the specialized message for our support requests.

## Requested Function
The locales key [``new_user``](https://github.com/helpyio/helpy/blob/master/config/locales/en.yml#L292) should be configurable to have several different messages. Especially the welcome message should be able to be configured per incoming email address (info@, support@, abuse@, etc.). Furthermore all self created tickets (from agents during a phone call for example) should also get different welcome messages.

**Comment by scott** [comment]
This is possible with the cloud hosted or on-premise cloud version by creating trigger responses that are filtered by channel, group, etc.  Closing from here.
