### ISSUE TITLE
search button at the sidebar

### ISSUE THREAD

**Issue by icadm** [helpyio/helpy#732]
search feature on the sidebar has no search button, screenshot:

![no label](https://i.imgur.com/67nPh11.png)

is it normal? looks like it's not normal as there's a button with missing label (grayish line) below the search input field

**Comment by JodyVanden** [comment]
Hey, did you do an inspect on this grayish line to check what it was? maybe that could help others

**Comment by tarnelope** [comment]
Hey there, looks like there should be a search icon displayed in the button. Let me dig into why it's not showing up.

**Comment by tarnelope** [comment]
The search area with the blank button still appears in the demo but it looks like the sidebar has been redesigned on the latest master branch and doesn't contain the search area anymore. Should this issue be considered closed then?

**Comment by scott** [comment]
It should still have the search.  It may be you are seeing a different theme- try add `?theme=light` to the url to force the theme and look in the sidebar.
