### ISSUE TITLE
Ticket creation through webhook fails

### ISSUE THREAD

**Issue by faburem** [helpyio/helpy#735]
Hello,
I tried to connect helpy to sendgrid today but get the following error stack when sendgrid is calling the webhook. Any help is greatly appreciated!

Error during failsafe response: ActionController::InvalidAuthenticityToken
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/request_forgery_protection.rb:181:in `handle_unverified_request'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/request_forgery_protection.rb:209:in `handle_unverified_request'
  /usr/local/bundle/gems/devise-3.5.6/lib/devise/controllers/helpers.rb:257:in `handle_unverified_request'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/request_forgery_protection.rb:204:in `verify_authenticity_token'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:432:in `block in make_lambda'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:164:in `block in halting'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `block in call'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `each'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:504:in `call'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/rescue.rb:29:in `process_action'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  /usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:137:in `process'
  /usr/local/bundle/gems/actionview-4.2.8/lib/action_view/rendering.rb:30:in `process'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal.rb:196:in `dispatch'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_controller/metal.rb:237:in `block in action'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:43:in `serve'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:43:in `block in serve'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `each'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `serve'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:817:in `call'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:47:in `render_exception'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:35:in `rescue in call'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /usr/local/bundle/gems/railties-4.2.8/lib/rails/rack/logger.rb:38:in `call_app'
  /usr/local/bundle/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `block in call'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:26:in `tagged'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `tagged'
  /usr/local/bundle/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `call'
  /usr/local/bundle/gems/request_store-1.3.1/lib/request_store/middleware.rb:9:in `call'
  /usr/local/bundle/gems/actionpack-4.2.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  /usr/local/bundle/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
  /usr/local/bundle/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
  /usr/local/bundle/gems/activesupport-4.2.8/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  /usr/local/bundle/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
  /usr/local/bundle/gems/railties-4.2.8/lib/rails/engine.rb:518:in `call'
  /usr/local/bundle/gems/railties-4.2.8/lib/rails/application.rb:165:in `call'
  /usr/local/bundle/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:562:in `process_client'
  /usr/local/bundle/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:658:in `worker_loop'
  /usr/local/bundle/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
  /usr/local/bundle/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:132:in `start'
  /usr/local/bundle/gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
  /usr/local/bundle/bin/unicorn:17:in `load'
  /usr/local/bundle/bin/unicorn:17:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'

**Comment by faburem** [comment]
Nevermind, this works just fine if you use the correct webhook url:
http://your.domain.com/email_processor

**Comment by elsurudo** [comment]
I am using the correct webhook URL, and still encountering this issue. Any ideas?

**Comment by scott** [comment]
Make sure that sendgrid is chosen in the settings > email panel.

**Comment by elsurudo** [comment]
Actually I am using Sparkpost – is there a known issue with the Sparkpost adapter?
