### ISSUE TITLE
Raspberry Pi + Docker installation

### ISSUE THREAD

**Issue by seevee** [helpyio/helpy#753]
I'm unable to get the application deployed via Docker on a Raspberry Pi.

Postgres works without issue, but helpy gets stuck in a restart loop:
`standard_init_linux.go:195: exec user process caused "exec format error"`

[The Docker team implemented support for multi-arch images a few months ago](https://blog.docker.com/2017/09/docker-official-images-now-multi-platform/) - it'd be really cool to be able to deploy helpy via Docker on ARM.

**Comment by scott** [comment]
It would be super cool if you figured this out and add a doc to the wiki about how you got it installed.  Unfortunately I am not too sure about that error.

**Comment by seevee** [comment]
The error seems to be common to running x86 Docker images on ARM architectures, but it certainly isn't very descriptive.

I will probably have some time to take a look at this next week! I'd love to help get this working.
