### ISSUE TITLE
Email with attachment spawning multiple tickets

### ISSUE THREAD

**Issue by sbwinn** [helpyio/helpy#755]
I sent in a test email to Help (via Sendgrid) with a PDF attachment.  The message subject and body are being put into multiple consecutive Helpy tickets but the attachment does not appear in any of them.  

Mail client: macOS 10.13.2 - Mail
Cloudinary account is setup in Helpy, but turned off.  

I can reproduced the issue.

**Comment by scott** [comment]
Do you have any idea how big the attachment is?  Or what the file format is?

**Comment by sbwinn** [comment]
It is a 115KB PDF file that I picked up off of the Internet. 

I thought about removing the Cloudinary credentials from Helpy completely to see if that made a difference.  Haven’t done it yet.  

Scott

**Comment by sbwinn** [comment]
Still an issue.  Tried from a different account.

**Comment by scott** [comment]
hey @sbwinn can you send me the pdf via email and let me try and recreate it.  I have test attachments extensively and have been able to attach pdf's without issue.  scott at helpy.io

**Comment by sbwinn** [comment]
Hey Scott, 

I attached it to the last message I sent you.  

Here it is again.  

I think it may be related to the macOS mail client.  I have had windows users send the same PDF into Helpy with no problem.  

Scott
