### ISSUE TITLE
When creating a ticket via email, any CC'd addresses should be added to the CC of the thread

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#767]
Currently you can add a CC to a ticket manually.  If a ticket is received via email, those CC'd on the email should be added to the ticket CC as well.

**Comment by CGA1123** [comment]
`Post#cc` is stored as a string.
How should we handle a CC containing multiple email addresses?

**Comment by scott** [comment]
I think it just expects them to comma delimted.  You can see how they are parsed in the mailer.

**Comment by CGA1123** [comment]
In that case #768 should be fine.

One thing I am not sure about is whether `Post#cc` should be set to the empty string (`""`) or `nil` when no cc is present in the incoming email.

`nil` might be a safer bet.
