### ISSUE TITLE
Add source to users model

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#785]
Because there are multiple ways to create users, it would be nice to track the source of how users are coming to the system.  This task would add a `source``string` column to the `User` model and set it if the user is added by `api`, `email`, `registration`, `admin_invite`, `ticket_form`, `widget` etc.

This source should be added to the user entity.

**Comment by CGA1123** [comment]
Would an `enum` be a better way to store this data?

**Comment by scott** [comment]
It could be, but the column is more for a logging purpose- so don't expect to need any kind of manipulation or querying based on this.  Also, I imagine people may want to add their own sources when adding users by API (from an app for example), which makes `enums` not suitable.
