### ISSUE TITLE
Unable to create ticket using unregistered email.

### ISSUE THREAD

**Issue by neutrinog** [helpyio/helpy#786]
I'm attempting to open a support ticket however I keep getting the following error:
```json
{"error":"User not registered. Insufficient access priviledges."}
```
I'm trying to submit the ticket with the `user_email` property set to an email that is not already registered with the help desk. I thought the new email is supposed to be automatically added.
If instead I use an email that's already in the system the ticket is created successfully. 

Here's a sample request:

```
Request URL:http://help.door43.org/api/v1/tickets?token=<an api token>
Request Method:POST
Status Code:401 Unauthorized
```

Payload
```
{
  body: "test",
  channel: "translationCore"
  name: "tC General Feedback"
  tag_list: "General Feedback, translationCore"
  user_email: "<my email>"
}
```

Is there a way to open a ticket without using an email/user id that's already registered?

**Comment by scott** [comment]
Hey @neutrinog it requires both an `user_email` and `user_name` if the user is unregistered.  If you provide both, it should go through.  It looks like there is a typo in the API docs, or at least it could be made clearer that it is required if the user is not registered.  Incidentally the docs for the `user_email` reference it differently. 

```
The user name for register a non-registered user. Required if user_email is not registered.
```

**Comment by neutrinog** [comment]
Thanks @scott, that was it.
Yes it would be helpful if the documentation was updated to be a bit clearer.
