### ISSUE TITLE
If reply voting is enabled, reply form does not work

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#79]
In a forum thread where reply voting is enabled, the inline reply forum does not submit unless you reload the page.  I narrowed it down to a turbo links issue, but didn't have time to dig further yet.

**Comment by rusikf** [comment]
@scott, Do you tell about this ? 
![screen](http://i.imgur.com/syG5q5u.jpg)
Voting here works fine. 

After clicking , Vote record is added( I checked in console )

**Comment by scott** [comment]
Thanks for looking into this issue.  My bug ticket was not clear enough- this screen capture shows the form which does not work.  Reply voting is different than topic voting (that your screenshot has).

![screen shot 2016-03-17 at 11 19 30 am](https://cloud.githubusercontent.com/assets/14369/13854650/2c660f58-ec32-11e5-994c-1bb19e3a66b2.png)
