### ISSUE TITLE
Installed with Docker getting Bad Gateway 502 error

### ISSUE THREAD

**Issue by ahansson89** [helpyio/helpy#809]
I installed with the steps in the wiki for Docker. The container runs, but it is returning 502 Bad Gateway.

**Comment by lpar** [comment]
I had this problem. Turned out the PostgreSQL container was restarting continuously because of an SELinux denial.

The fix:

```
diff --git a/docker-compose.yml b/docker-compose.yml
index c4901648..7b48e1af 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -36,7 +36,7 @@ services:
       - back
     env_file: docker/.env
     volumes:
-      - ./postgres:/var/lib/postgresql/data
+      - ./postgres:/var/lib/postgresql/data:z
 
 volumes:
   rails-assets:
```

Found via [Docker PostgreSQL issue 116](https://github.com/docker-library/postgres/issues/116).

**Comment by Sarke** [comment]
Note as well that is can take a couple of minutes for the assets to be compiled and the website to become available.

**Comment by alexdg** [comment]
had to remove the "/data" and force 9.3 version.

postgres:
    image: postgres:9.3
    restart: always
    networks:
      - back
    env_file: docker/.env
    volumes:
      - ./postgres:/var/lib/postgresql
