### ISSUE TITLE
Upload PDF?

### ISSUE THREAD

**Issue by jonasleimgruber** [helpyio/helpy#81]
It's not possible to upload PDF's with the ticket. It would be great if that's possible as well.

**Comment by rschaerer** [comment]
Cloudinary seems to support this filetype. So this might be quite easy to enable in helpy?

**Comment by scott** [comment]
Yes, I believe Cloudinary does, and enabling Helpy to accept the file type should be fairly easy.  However, Helpy currently shows thumbnails of attached images, and I think there would be a little work there to support PDF files (maybe with an icon placeholder.)  If someone wants to take a crack at it and send a PR, I would be happy to help/review.

**Comment by rschaerer** [comment]
About the thumbnail issue: [Cloudinary can generate thumbnails for PDF documents](http://cloudinary.com/blog/uploading_converting_and_generating_thumbnails_for_pdf_documents).

Let's see if someone comes around with a PR. Otherwise, maybe i'll dig into that later.
