### ISSUE TITLE
Third party SMTP service

### ISSUE THREAD

**Issue by hadifarnoud** [helpyio/helpy#812]
Helpy only supports Sendgrid and a few other services. We recently switched to http://elasticemail.com

I tried to set it up as "Sendgrid" and changed the ports according to documentation on Elastiemail. it does not work. any advice?

**Comment by scott** [comment]
Hi @hadifarnoud elasticemail looks pretty 🎉!  In order to get it working in Helpy, you will need to add an adapter gem.  Here is an example of the one for SendGrid https://github.com/thoughtbot/griddler-sendgrid

It looks like no one else has written an adapter for ElasticEmail so that might be the place to start!

**Comment by hadifarnoud** [comment]
Elasticemail is awesome and cheap! we recently switched. I was hoping a general SMTP setting work for Helpy. is that possible? that makes Helpy compatible with any transactional email service

**Comment by hadifarnoud** [comment]
seems like that griddler adapter is for parsing incoming emails. my request was setting normal SMTP for outgoing emails. there is no way to set a SMTP service other than the ones allowed in Helpy

**Comment by scott** [comment]
Actually thats not true.  The dropdown is only for selecting the inbound parse provider.  You can enter any smtp you want- I have tested it with a handful of different ones and all worked.  Not sure what the problem is with ElasticEmail...  but it should work 🤞

**Comment by hadifarnoud** [comment]
I can confirm that third party SMTP works just fine. there was a networking issue on our side.
