### ISSUE TITLE
Internal KB articles are shown multiple times

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#828]
This is a rare bug where a translated category is duplicated in the UI, only if the user is viewing the admin in the non default locale.  To reproduce- create a new internal category and doc, then edit the category to create an alternate locale version.  Now view the internal docs using the same alternate locale and you will see the doc repeated.

**Comment by dhoangk07** [comment]
Hi @scott, I've tried to reproduce the bug as your description but it doesn't happen on my end. Could you give me more details of steps or record the video? It's definitely helpful. Thanks

**Comment by scott** [comment]
Hey @dhoangk07 let me do that.

**Comment by scott** [comment]
Here take a look at this- https://www.screencast.com/t/CTz6F9e0W0 . If you don't have it, you might grap the "Quick Language Switcher" add on for Chrome, makes switching between locales much easier.

**Comment by dhoangk07** [comment]
Hi @scott I have PR to fix the issue. Please take a look https://github.com/helpyio/helpy/pull/904
