### ISSUE TITLE
replace "on/off" switches with language neutral IOS style

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#842]

**Comment by trevormerritt** [comment]
Hi Scott,

Please see Pull 847 and let me know if it is what you were thinking.

**Comment by scott** [comment]
Thats a pretty easy way to do it 👍 Can you hack on the CSS to make it look more like this: https://codeburst.io/pure-css3-input-as-the-ios-checkbox-8b6347d5cefb

**Comment by trevormerritt** [comment]
Using the notes from https://github.com/Bttstrp/bootstrap-switch/issues/555 I pushed another commit.
