### ISSUE TITLE
Validate URL in settings

### ISSUE THREAD

**Issue by scott** [helpyio/helpy#854]
Currently the site URL setting will allow anything.  If the user mistakenly enters something that is not a URL, parts of Helpy will not work correctly.

**Comment by scott** [comment]
#873

**Comment by ozmar-11** [comment]
can I take this one?

**Comment by scott** [comment]
Hi @ozmar-11 that would be great! You'll notice that some work was already done in #986 so if you would review my notes there that might be helpful.
