### ISSUE TITLE
Change logo in email

### ISSUE THREAD

**Issue by sGerli** [helpyio/helpy#866]
I've been unable to change the logo in the email through the web interface. And after looking through the email template files it looks like it's hardcoded to the Helpy `logo.png`.
https://github.com/helpyio/helpy/blob/eea068fcc6772828698530c272512f06a5ae0a8d/app/views/layouts/mailer.html.erb#L17

**Comment by scott** [comment]
Hi @sGerli thats right.  The logo is in fact hardcoded for notifications to the agent/admin team.  Emails sent to customers use a different mailer `PostMailer`.  If you want to change the logo used across the whole system, just overwrite `logo.png` with your own.
