### ISSUE TITLE
Agent users can create admin users via the API

### ISSUE THREAD

**Issue by pjuhasz** [helpyio/helpy#870]
Any user with the agent role can create an API key, then use the /api/v1/users endpoint to create a new user with an admin role. This is a security issue: any agent can trivially gain full admin privileges, and also this is in direct contradiction with the documentation (which states that API keys issued to agents are have limited power).

Steps to reproduce: 
- Log in to demo.helpy.io with the default admin user
- Create an API key, save it somewhere
- Log out
- Create the agent user via the API:
curl -X POST  https://demo.helpy.io/api/v1/users?token=<admin's apikey> -F"name=Test Agent" -F"email=testagent@company.com" -F"password=Password123" -F"role=agent"
- Log in to demo.helpy.io with the new agent user, using the address and password from the command above
- Create an API key, save it somewhere
- Log out
- Create the admin user via the API:
curl -X POST  https://demo.helpy.io/api/v1/users?token=<agent's apikey> -F"name=Test Admin" -F"email=testadmin@company.com" -F"password=Password123" -F"role=admin"
- Log in to demo.helpy.io with the new admin user, enjoy your admin powers!

Proposed fix:
Frankly, I don't see why agents should be able to issue API keys at all. At the very least, this should be an option that can be disabled in settings.yml or somewhere.

**Comment by scott** [comment]
+1 for the option, although I agree it is probably not necessary.  I think a nicer approach might be to make it possible for admins to create api keys for their agents if needed.
