### ISSUE TITLE
Flat theme: include listing of locales above frontend header

### ISSUE THREAD

**Issue by l3ku** [helpyio/helpy#882]
Hi! We are using the Helpy Flat UI theme and I noticed that it could be more convenient for the user to directly be able to switch locales from the header and that all locales are listed side-to-side instead of a dropdown. Somewhat like this:

![screen shot 2018-08-22 at 8 33 09](https://user-images.githubusercontent.com/24781811/44444557-0cc37f80-a5e6-11e8-9973-24f33ceac6e1.png)

By looking through the codebase, I found out that files `/app/themes/flat/views/layouts/_header.html.erb` and `/app/themes/flat/views/layouts/_above_header.html.erb` already exist, but they seem not to be used at all. Should the header layout be included in `/app/themes/flat/views/layouts/flat.html.erb` or have I understood something incorrectly? It seems to me that the header is currently outputted from lines https://github.com/helpyio/helpy/blob/634145490bc8a14fe5750c8ac05537bf9117eac6/app/themes/flat/views/layouts/flat.html.erb#L54-L73
instead of using the header layout.

I'm happy to make a PR about this.

**Comment by scott** [comment]
@l3ku I would probably do this by inserting some javascript into your design.  You can accomplish this by going to settings > design then scroll down to the footer js.  Add a script like this:

```
<script>
  var $target = $('header');
  var includedLocales = ['en','fr','fi'];
  var currentUrl = window.location.pathname;
  var currentLocale = currentUrl.split("/")[0];
  var localePicker = "";
  var $picker = $('<ul class="list-inline"/>');
  $.each(includedLocales, function(i,locale){
    $picker.append($("<li><a href='/" + locale + "'>" + locale + "</li>"))
  });
  $target.find('div').find('div').find('div:nth-child(2)').prepend($picker);

</script>
```
This will run on every page of the helpcenter and add the locale links accordingly.  You can additional styling as you see fit, or use a regex to match the exact URL of the page the user is on (probably unnecessary).
