### ISSUE TITLE
Suggestion / Request: use Dependabot to keep dependencies up-to-date

### ISSUE THREAD

**Issue by greysteil** [helpyio/helpy#906]
First of all, thanks for Helpy!

I've got a suggestion / request: would you be up for using [Dependabot](https://dependabot.com) to automatically create dependency update PRs for this repo? I ran it against my fork and it generated [these PRs](https://github.com/greysteil/helpy/pulls). I'll port the `timecop` one across to this repo now. It will also monitor the repo for insecure dependencies, and create PRs for those.

I built Dependabot and give it away for free to open source projects (partly for the exposure, but mainly because it feels good to give back and because the feedback is incredibly useful). I'm honestly only suggesting it because I hope it can save you some time doing work that is otherwise monotonous.

If you do decide to give Dependabot a go the easiest URL to add it from is https://github.com/apps/dependabot (alternatively you can go through the [GitHub Marketplace](https://github.com/marketplace/dependabot), but the flow there can be a little confusing for open-source repos on an organisation account).

:octocat:

**Comment by greysteil** [comment]
Thanks @scott. Let me know any feedback! It should be super solid for Ruby, since it's built in it - most of the source code is [here](https://github.com/dependabot/dependabot-core).

Happy to help out with the initial PRs to get Helpy up-to-date.

**Comment by scott** [comment]
Hey @greysteil I have been liking dependabot, but I got tired of all the PRs at first and just did a bundle update (actually based on some update work @CGA1123 had done earlier in the year).

**Comment by greysteil** [comment]
That makes a tonne of sense - that initial work to get up-to-date can be a real pain.

Anything I can help with? Really psyched to have you using it on Helpy 🙂
