### ISSUE TITLE
"Thank you" missing in translation

### ISSUE THREAD

**Issue by msbt** [helpyio/helpy#948]
As mentioned on slack: The "thank you" text after creating a ticket can't be translated at the moment

**Comment by dhoangk07** [comment]
Dear @msbt, @scott 
I already added translate `thank you` and `message` on locale file. Please take a look.
Thanks in advance.

**Comment by msbt** [comment]
@dhoangk07 I don't know about the code, but the translations are looking good, except I would go with "Nachricht" instead of "Botschaft" for the german message translation. Maybe @scott can take a look at the rest. Again, thanks for your efforts and sorry for the delay

**Comment by dhoangk07** [comment]
@msbt , I will change german message translation from `Botschaft` to `Nachricht` after @scott take a look at.

**Comment by scott** [comment]
@dhoangk07 @msbt I already merged these, but please open a new PR if we need to update the translations.  I don't know any German so I can't help much there.

**Comment by dhoangk07** [comment]
Hey @scott @msbt 
I already change locale of German: ”Nachricht" instead of "Botschaft"
Please take a look.
Best regards
